project_id = "kozdctbbvrnyddlftmvf"

[functions.phone-auth]
verify_jwt = true

[functions.admin-blog-agent]
verify_jwt = false

[functions.admin-data-cleaner]
verify_jwt = false

[functions.cat-response-analyzer]
verify_jwt = false
