import Link from "next/link";
import { studyApi, type Entity } from "@/lib/api";
import { parseResourceSlug } from "@/lib/study";

const text = (entity: Entity, key: string) => typeof entity[key] === "string" ? String(entity[key]) : "";

export async function ResourceDirectory({ slug, searchParams }: { slug?: string; searchParams: Promise<{ classNumber?: string; boardSlug?: string; subjectSlug?: string; type?: string; q?: string }> }) {
  const query = await searchParams; const preset = parseResourceSlug(slug);
  const filters = { classNumber: query.classNumber ? Number(query.classNumber) : preset.classNumber, boardSlug: query.boardSlug || preset.boardSlug, subjectSlug: query.subjectSlug || preset.subjectSlug, type: query.type || preset.type, q: query.q, limit: 500 };
  const resources = await studyApi.resources(filters);
  return <main className="container page"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/study-material">Study material</Link><span>/</span><span>Resources</span></nav><header className="page-heading"><p className="eyebrow">Free study resources</p><h1>{slug ? slug.replace(/-/g, " ") : "Notes, papers and learning resources"}</h1><p>Search published resources by class, board, subject and type. Download verification continues through the existing OTP flow during migration.</p></header>
    <form className="resource-filters"><label>Search<input name="q" defaultValue={query.q} placeholder="Resource or subject" /></label><label>Class<select name="classNumber" defaultValue={filters.classNumber || ""}><option value="">All</option>{[8,9,10,11,12].map((item) => <option key={item}>{item}</option>)}</select></label><label>Board<input name="boardSlug" defaultValue={filters.boardSlug} placeholder="cbse" /></label><label>Subject<input name="subjectSlug" defaultValue={filters.subjectSlug} placeholder="physics" /></label><label>Type<select name="type" defaultValue={filters.type || ""}><option value="">All</option><option value="pyq">Previous papers</option><option value="ncert">NCERT</option><option value="notes">Notes</option><option value="sample">Sample papers</option></select></label><button>Filter</button></form>
    <p className="result-count">{resources.length} resource{resources.length === 1 ? "" : "s"}</p><section className="resource-grid">{resources.map((resource) => { const subject = resource.subject && typeof resource.subject === "object" ? resource.subject as Entity : {}; const chapter = resource.chapter && typeof resource.chapter === "object" ? resource.chapter as Entity : {}; const path = `/study-material/class-${subject.class_num}/${subject.board_slug}/${subject.slug}${chapter.slug ? `/${chapter.slug}` : ""}`; return <article key={String(resource.id)}><p className="eyebrow">{text(resource, "resource_type")} {text(resource, "year")}</p><h2><Link href={path}>{String(resource.title)}</Link></h2><p>{text(resource, "description")}</p><div className="facts"><span>Class {String(subject.class_num)}</span><span>{String(subject.board_slug || "").toUpperCase()}</span><span>{String(subject.name || "")}</span></div><Link className="text-link" href={path}>View resource →</Link></article>; })}</section>{resources.length === 0 && <p>No resources match these filters.</p>}</main>;
}
