package com.dekhocampus.platform.config;
import java.util.List; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.context.annotation.Bean; import org.springframework.context.annotation.Configuration; import org.springframework.http.HttpMethod; import org.springframework.security.config.Customizer; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.oauth2.jwt.JwtDecoder; import org.springframework.security.oauth2.jwt.NimbusJwtDecoder; import org.springframework.security.web.SecurityFilterChain; import org.springframework.web.cors.CorsConfiguration; import org.springframework.web.cors.CorsConfigurationSource; import org.springframework.web.cors.UrlBasedCorsConfigurationSource;
@Configuration @EnableMethodSecurity public class SecurityConfig {
 @Bean CorsConfigurationSource cors(@Value("${app.cors-origin}") String origin){ var c=new CorsConfiguration(); c.setAllowedOrigins(List.of(origin)); c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS")); c.setAllowedHeaders(List.of("Authorization","Content-Type","X-Request-Id","X-CSRF-Token")); c.setAllowCredentials(true); var s=new UrlBasedCorsConfigurationSource(); s.registerCorsConfiguration("/**",c); return s; }
 @Bean @ConditionalOnProperty(name="security.require-auth",havingValue="true",matchIfMissing=true) JwtDecoder jwtDecoder(@Value("${security.jwks-uri}") String uri){return NimbusJwtDecoder.withJwkSetUri(uri).build();}
 @Bean @ConditionalOnProperty(name="security.require-auth",havingValue="true",matchIfMissing=true) SecurityFilterChain secure(HttpSecurity http)throws Exception{return common(http).authorizeHttpRequests(a->a.requestMatchers("/actuator/health/**","/api/v1/content/**","/api/v1/about","/api/v1/study/**","/api/v1/college-study/**","/api/v1/redirects/**","/api/v1/auth/login","/api/v1/auth/refresh").permitAll().requestMatchers(HttpMethod.OPTIONS,"/**").permitAll().anyRequest().authenticated()).oauth2ResourceServer(o->o.jwt(Customizer.withDefaults())).build();}
 @Bean @ConditionalOnProperty(name="security.require-auth",havingValue="false") SecurityFilterChain local(HttpSecurity http)throws Exception{return common(http).authorizeHttpRequests(a->a.anyRequest().permitAll()).build();}
 private HttpSecurity common(HttpSecurity http)throws Exception{return http.cors(Customizer.withDefaults()).csrf(c->c.ignoringRequestMatchers("/api/v1/auth/**","/api/v1/functions/**")).headers(h->h.contentSecurityPolicy(c->c.policyDirectives("default-src 'none'; frame-ancestors 'none'")));
 }
}
