import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { JsonLd } from "@/components/JsonLd";
import { collegeStudyApi } from "@/lib/api";
import { parseSemesterSlug } from "@/lib/college-study";
import { absoluteUrl } from "@/lib/site";

const text = (item: Record<string, unknown>, key: string) => String(item[key] || "");
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ programSlug: string; universitySlug: string; semSlug: string; subjectSlug: string }> }): Promise<Metadata> { const values = await params; return { title: `${values.subjectSlug.replaceAll("-", " ")} notes and previous papers`, alternates: { canonical: absoluteUrl(`/college-study-material/${values.programSlug}/${values.universitySlug}/${values.semSlug}/${values.subjectSlug}`) } }; }
export default async function CollegeSubjectPage({ params }: { params: Promise<{ programSlug: string; universitySlug: string; semSlug: string; subjectSlug: string }> }) { const values = await params; const semester = parseSemesterSlug(values.semSlug); if (!semester) redirect(`/college-study-material/${values.programSlug}/${values.universitySlug}`); const data = await collegeStudyApi.subject(values.programSlug, values.universitySlug, semester, values.subjectSlug); const subject = data.subject; const groups = data.resources.reduce<Record<string, typeof data.resources>>((all, resource) => { const key = text(resource, "resource_type") || "notes"; (all[key] ||= []).push(resource); return all; }, {}); return <main className="container page"><JsonLd data={{ "@context": "https://schema.org", "@type": "LearningResource", name: text(subject, "name"), educationalLevel: `Semester ${semester}`, url: absoluteUrl(`/college-study-material/${values.programSlug}/${values.universitySlug}/${values.semSlug}/${values.subjectSlug}`) }} /><nav className="breadcrumbs"><Link href={`/college-study-material/${values.programSlug}/${values.universitySlug}/${values.semSlug}`}>Semester {semester}</Link><span>/</span><span>{text(subject, "name")}</span></nav><header className="page-heading"><p className="eyebrow">{text(subject, "code")} · Semester {semester}</p><h1>{text(subject, "name")}</h1><p>{text(subject, "description") || "Notes, previous question papers, lab manuals and reference material."}</p></header>{Object.entries(groups).map(([type, resources]) => <section className="info-section" key={type}><h2>{type.replaceAll("-", " ")}</h2><div className="subject-grid">{resources.map((resource) => <article key={text(resource, "id")}><h3>{text(resource, "title")}</h3><p>{text(resource, "description") || (resource.year ? `Year ${resource.year}` : "Study resource")}</p>{resource.download_available ? <p className="status-note">Download remains protected by the verified access flow.</p> : <p>File coming soon.</p>}</article>)}</div></section>)}</main>; }
