-- Generated from data/college-official-enrichment/batch-003-iit-delhi-course-catalogue.json
-- Replaces generic degree-family rows with a complete official course catalogue.
-- Images and logos are deliberately untouched. Unverified fees remain NULL.
BEGIN;

DO $verify$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.colleges WHERE slug = 'iit-delhi') THEN
    RAISE EXCEPTION 'College slug not found: iit-delhi';
  END IF;
END
$verify$;

UPDATE public.colleges
SET
  related_courses = ARRAY['btech', 'bachelor-of-science-bsc', 'bdes', 'master-of-technology-mtech', 'msc', 'mba', 'ma', 'phd']::text[],
  courses_count = 129,
  data_source_urls = COALESCE(data_source_urls, '{}'::jsonb) || '{"course_catalogue":["https://home.iitd.ac.in/uploads/General%20Information/CoS-02025-56__General-Rules__03-02-2026.pdf","https://academics.iitd.ac.in/undergraduate/","https://academics.iitd.ac.in/postgraduate-programs/","https://academics.iitd.ac.in/m-tech/","https://academics.iitd.ac.in/ph-d/","https://home.iitd.ac.in/uploads/PROSPECTUS%202026-27.pdf"],"course_catalogue_scope":"complete_advertised_programmes_and_specialisations","course_catalogue_checked_at":"2026-07-29","fee_verification":"programme_catalogue_verified_but_fee_amounts_not_mapped_by_programme_and_category","batch":"college-course-catalogue-003"}'::jsonb,
  data_clean_method = 'official_source',
  data_clean_state = 'verified',
  data_clean_audit_note = 'Complete advertised programme and specialisation catalogue verified from official 2026-27 academic pages in college-course-catalogue-003. Fees remain blank because the official circular varies by programme and student category.',
  data_quality_score = 92,
  data_verified_at = '2026-07-29T00:00:00+05:30'::timestamptz,
  data_last_checked_at = '2026-07-29T00:00:00+05:30'::timestamptz,
  official_source_cleaned_at = '2026-07-29T00:00:00+05:30'::timestamptz,
  official_source_clean_pass_count = COALESCE(official_source_clean_pass_count, 0) + 1,
  ai_clean_pass_count = COALESCE(ai_clean_pass_count, 0) + 1,
  official_courses_verified = true,
  official_fees_verified = false,
  requires_official_source_refresh = false,
  updated_at = now()
WHERE slug = 'iit-delhi';

DELETE FROM public.course_fees WHERE college_slug = 'iit-delhi';

INSERT INTO public.course_fees (college_slug, course_slug, course_name, fee_amount, fee_type, year)
VALUES
  ('iit-delhi', 'bdes', 'Bachelor of Design', NULL, NULL, '2026'),
  ('iit-delhi', 'bs-chemistry', 'BS in Chemistry', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-engineering-computational-mechanics', 'BTech in Engineering and Computational Mechanics', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-biochemical-engineering-biotechnology', 'BTech in Biochemical Engineering and Biotechnology', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-chemical-engineering', 'BTech in Chemical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-computer-science-engineering', 'BTech in Computer Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-civil-engineering', 'BTech in Civil Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-design', 'BTech in Design', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-electrical-engineering', 'BTech in Electrical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-electrical-engineering-power-automation', 'BTech in Electrical Engineering (Power and Automation)', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-energy-engineering', 'BTech in Energy Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-materials-engineering', 'BTech in Materials Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-mathematics-computing', 'BTech in Mathematics and Computing', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-mechanical-engineering', 'BTech in Mechanical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-production-industrial-engineering', 'BTech in Production and Industrial Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-engineering-physics', 'BTech in Engineering Physics', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-textile-fibre-engineering', 'BTech in Textile and Fibre Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-mtech-chemical-engineering', 'BTech and MTech Dual Degree in Chemical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-mtech-computer-science-engineering', 'BTech and MTech Dual Degree in Computer Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'btech-mtech-mathematics-computing', 'BTech and MTech Dual Degree in Mathematics and Computing', NULL, NULL, '2026'),
  ('iit-delhi', 'ma-culture-society-thought', 'MA in Culture, Society and Thought', NULL, NULL, '2026'),
  ('iit-delhi', 'mba', 'Master of Business Administration', NULL, NULL, '2026'),
  ('iit-delhi', 'mba-telecommunication-systems-management', 'MBA in Telecommunication Systems Management', NULL, NULL, '2026'),
  ('iit-delhi', 'executive-mba', 'Executive Master of Business Administration', NULL, NULL, '2026'),
  ('iit-delhi', 'mdes-industrial-design', 'MDes in Industrial Design', NULL, NULL, '2026'),
  ('iit-delhi', 'master-public-policy', 'Master of Public Policy', NULL, NULL, '2026'),
  ('iit-delhi', 'msc-chemistry', 'MSc in Chemistry', NULL, NULL, '2026'),
  ('iit-delhi', 'msc-cognitive-science', 'MSc in Cognitive Science', NULL, NULL, '2026'),
  ('iit-delhi', 'msc-economics', 'MSc in Economics', NULL, NULL, '2026'),
  ('iit-delhi', 'msc-mathematics', 'MSc in Mathematics', NULL, NULL, '2026'),
  ('iit-delhi', 'msc-physics', 'MSc in Physics', NULL, NULL, '2026'),
  ('iit-delhi', 'msc-biological-sciences', 'MSc in Biological Sciences', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-information-technology', 'MS Research in Information Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-applied-mechanics', 'MS Research in Applied Mechanics', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-atmospheric-oceanic-sciences', 'MS Research in Atmospheric and Oceanic Sciences', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-automotive-research-tribology', 'MS Research in Automotive Research and Tribology', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-healthcare-technology', 'MS Research in Healthcare Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-telecommunication-technology-management', 'MS Research in Telecommunication Technology and Management', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-biochemical-engineering-biotechnology', 'MS Research in Biochemical Engineering and Biotechnology', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-chemical-engineering', 'MS Research in Chemical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-civil-engineering', 'MS Research in Civil Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-computer-science-engineering', 'MS Research in Computer Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-electrical-engineering', 'MS Research in Electrical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-energy-science-engineering', 'MS Research in Energy Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-materials-engineering', 'MS Research in Materials Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-mechanical-engineering', 'MS Research in Mechanical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-biological-sciences', 'MS Research in Biological Sciences', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-optics', 'MS Research in Optics', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-vlsi-design-tools-technology', 'MS Research in VLSI Design Tools and Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-sensors-instrumentation-cyber-physical-systems', 'MS Research in Sensors, Instrumentation and Cyber-Physical Systems Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-transportation-safety-injury-prevention', 'MS Research in Transportation Safety and Injury Prevention', NULL, NULL, '2026'),
  ('iit-delhi', 'ms-research-machine-intelligence-data-science', 'MS Research in Machine Intelligence and Data Science', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-engineering-analysis-design', 'MTech in Engineering Analysis and Design', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-biomolecular-bioprocess-engineering', 'MTech in Biomolecular and Bioprocess Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-chemical-engineering', 'MTech in Chemical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-molecular-engineering-chemical-synthesis-analysis', 'MTech in Molecular Engineering: Chemical Synthesis and Analysis', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-geotechnical-geoenvironmental-engineering', 'MTech in Geotechnical and Geoenvironmental Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-rock-engineering-underground-structures', 'MTech in Rock Engineering and Underground Structures', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-structural-engineering', 'MTech in Structural Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-water-resources-engineering', 'MTech in Water Resources Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-construction-engineering-management', 'MTech in Construction Engineering and Management', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-construction-technology-management', 'MTech in Construction Technology and Management', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-environmental-engineering-management', 'MTech in Environmental Engineering and Management', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-transportation-engineering', 'MTech in Transportation Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-computer-science-engineering', 'MTech in Computer Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-communications-engineering', 'MTech in Communications Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-computer-technology', 'MTech in Computer Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-control-automation', 'MTech in Control and Automation', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-integrated-electronics-circuits', 'MTech in Integrated Electronics and Circuits', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-power-electronics-electrical-machines-drives', 'MTech in Power Electronics, Electrical Machines and Drives', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-power-systems', 'MTech in Power Systems', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-energy-environment-technologies-management', 'MTech in Energy and Environment Technologies and Management', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-renewable-energy-technologies-management', 'MTech in Renewable Energy Technologies and Management', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-materials-science-engineering', 'MTech in Materials Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-mechanical-design', 'MTech in Mechanical Design', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-industrial-engineering', 'MTech in Industrial Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-production-engineering', 'MTech in Production Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-thermal-engineering', 'MTech in Thermal Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-applied-optics', 'MTech in Applied Optics', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-solid-state-materials', 'MTech in Solid State Materials', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-fibre-engineering-textile-chemical-processing', 'MTech in Fibre Engineering and Textile Chemical Processing', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-textile-engineering', 'MTech in Textile Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-radio-frequency-design-technology', 'MTech in Radio Frequency Design and Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-atmospheric-oceanic-science-technology', 'MTech in Atmospheric-Oceanic Science and Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-electric-mobility', 'MTech in Electric Mobility', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-biomedical-engineering', 'MTech in Biomedical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-photonics', 'MTech in Photonics', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-machine-intelligence-data-science', 'MTech in Machine Intelligence and Data Science', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-cyber-security', 'MTech in Cyber Security', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-instrument-technology', 'MTech in Instrument Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-optoelectronics-optical-communication', 'MTech in Optoelectronics and Optical Communication', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-telecommunication-technology-management', 'MTech in Telecommunication Technology Management', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-robotics', 'MTech in Robotics', NULL, NULL, '2026'),
  ('iit-delhi', 'mtech-vlsi-design-tools-technology', 'MTech in VLSI Design Tools and Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'pg-diploma-naval-construction', 'PG DIIT in Naval Construction', NULL, NULL, '2026'),
  ('iit-delhi', 'pg-diploma-visionary-leadership-manufacturing', 'Joint PG Diploma in Visionary Leadership in Manufacturing', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-applied-mechanics', 'PhD in Applied Mechanics', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-applied-research-electronics', 'PhD in Applied Research in Electronics', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-artificial-intelligence', 'PhD in Artificial Intelligence', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-atmospheric-sciences', 'PhD in Atmospheric Sciences', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-automotive-research-tribology', 'PhD in Automotive Research and Tribology', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-biochemical-engineering-biotechnology', 'PhD in Biochemical Engineering and Biotechnology', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-biological-sciences', 'PhD in Biological Sciences', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-biomedical-engineering', 'PhD in Biomedical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-chemical-engineering', 'PhD in Chemical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-chemistry', 'PhD in Chemistry', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-civil-environmental-engineering', 'PhD in Civil and Environmental Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-computer-science-engineering', 'PhD in Computer Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-design', 'PhD in Design', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-electrical-engineering', 'PhD in Electrical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-energy-science-engineering', 'PhD in Energy Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-humanities-social-sciences', 'PhD in Humanities and Social Sciences', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-information-technology', 'PhD in Information Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-interdisciplinary-research', 'PhD in Interdisciplinary Research', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-management-studies', 'PhD in Management Studies', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-materials-science-engineering', 'PhD in Materials Science and Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-mathematics', 'PhD in Mathematics', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-mechanical-engineering', 'PhD in Mechanical Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-optics-photonics', 'PhD in Optics and Photonics', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-physics', 'PhD in Physics', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-public-policy', 'PhD in Public Policy', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-rural-development-technology', 'PhD in Rural Development and Technology', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-sensors-instrumentation-cyber-physical-systems', 'PhD in Sensors, Instrumentation and Cyber-Physical Systems Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-telecommunication-technology-management', 'PhD in Telecommunication Technology and Management', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-textile-fibre-engineering', 'PhD in Textile and Fibre Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-transportation-research-injury-prevention', 'PhD in Transportation Research and Injury Prevention', NULL, NULL, '2026'),
  ('iit-delhi', 'phd-value-education-engineering', 'PhD in Value Education in Engineering', NULL, NULL, '2026'),
  ('iit-delhi', 'joint-phd-university-queensland', 'Joint PhD Programme with the University of Queensland', NULL, NULL, '2026'),
  ('iit-delhi', 'joint-phd-national-yang-ming-chiao-tung-university', 'Joint PhD Programme with National Yang Ming Chiao Tung University', NULL, NULL, '2026');

NOTIFY pgrst, 'reload schema';
COMMIT;
