-- Direct, source-backed 2026 exam curation: batch 02.
-- Facts are limited to official exam authorities and first-party bulletins.

UPDATE public.exams
SET
  name = 'JEE Main',
  short_name = 'JEE Main',
  full_name = 'Joint Entrance Examination (Main) 2026',
  category = 'Engineering',
  categories = ARRAY['Engineering', 'Architecture', 'Planning'],
  level = 'Undergraduate',
  exam_type = 'National entrance exam',
  mode = 'Computer-based test; B.Arch drawing is conducted offline',
  frequency = 'Two sessions in 2026',
  duration = '3 hours; 3 hours 30 minutes when both Paper 2A and Paper 2B are taken',
  language = 'English, Hindi and regional languages listed in the official bulletin',
  application_mode = 'Online',
  application_start_date = '31 October 2025 for Session 1',
  application_end_date = '27 November 2025 for Session 1',
  exam_date = '21-30 January 2026 (Session 1); 2-9 April 2026 (Session 2)',
  status = 'Result Declared',
  official_website = 'https://jeemain.nta.nic.in/',
  website = 'https://jeemain.nta.nic.in/',
  brochure_url = 'https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2025/11/202511021649722475.pdf',
  registration_url = 'https://jeemain.nta.nic.in/',
  eligibility = 'Students who passed Class 12 or an equivalent examination in 2024 or 2025, or appeared in 2026, could take JEE Main 2026. JEE Main itself had no age limit, although participating institutes could apply their own admission rules.',
  description = 'JEE Main 2026 was the national entrance test for B.E./B.Tech, B.Arch and B.Planning admissions. It also served as the qualifying route to JEE Advanced for eligible engineering aspirants.',
  page_summary = 'JEE Main 2026 ran in January and April sessions. Paper 1 covered B.E./B.Tech admission, Paper 2A covered B.Arch and Paper 2B covered B.Planning.',
  summary_content = '<h2>What was JEE Main 2026?</h2><p>JEE Main was the first major engineering entrance milestone of 2026. Students could appear in one or both sessions, and NTA used the better applicable score while preparing the final result.</p><p>Paper 1 was meant for B.E./B.Tech aspirants. Architecture and planning candidates used Paper 2A and Paper 2B respectively. Students should use the official NTA portal for score cards and final notices.</p>',
  application_process = '<h2>How the application worked</h2><ol><li>Register through the official JEE Main portal and create the application number.</li><li>Complete personal, academic and exam-city details.</li><li>Upload the required documents and pay the application fee.</li><li>Download the confirmation page and later use the same portal for city intimation, admit card and score card.</li></ol>',
  exam_pattern = 'Paper 1 tested Physics, Chemistry and Mathematics. Paper 2A combined Mathematics, Aptitude and Drawing, while Paper 2B combined Mathematics, Aptitude and Planning. MCQs and numerical-value questions used +4 for a correct response and -1 for an incorrect response.',
  dates_content = '<h2>JEE Main 2026 timeline</h2><ul><li>Session 1 application opened on 31 October 2025 and closed on 27 November 2025.</li><li>Session 1 examinations were scheduled from 21 to 30 January 2026.</li><li>Session 2 examinations were scheduled from 2 to 9 April 2026.</li><li>NTA subsequently published answer keys and score cards for both sessions.</li></ul>',
  result_content = '<h2>JEE Main 2026 result</h2><p>NTA released session-wise score cards and final NTA scores on the official website. Candidates should use the official login for their score card and follow JoSAA or the relevant state and institute counselling process separately.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Session 1 Application Start','date','31 October 2025'),
    jsonb_build_object('event','Session 1 Application End','date','27 November 2025'),
    jsonb_build_object('event','Session 1 Exam Window','date','21-30 January 2026'),
    jsonb_build_object('event','Session 2 Exam Window','date','2-9 April 2026'),
    jsonb_build_object('event','Session 2 Paper 1 Result','date','Declared')
  ),
  meta_title = 'JEE Main 2026: Official Dates, Eligibility, Pattern and Results',
  meta_description = 'Understand JEE Main 2026 session dates, eligibility, Paper 1 and Paper 2 pattern, official score-card updates and the next admission steps.',
  meta_keywords = 'JEE Main 2026, JEE Main result, JEE Main dates, JEE Main eligibility, JEE Main pattern, NTA JEE',
  data_source_urls = jsonb_build_array(
    'https://jeemain.nta.nic.in/',
    'https://jeemain.nta.nic.in/information-bulletin/',
    'https://jeemain.nta.nic.in/public-notices/',
    'https://cdnbbsr.s3waas.gov.in/s3f8e59f4b2fe7c5705bf878bbd494ccdf/uploads/2025/11/202511021649722475.pdf'
  ),
  data_verified_at = now(),
  data_last_checked_at = now(),
  data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned',
  updated_at = now()
WHERE slug = 'jee-main-2026';

UPDATE public.exams
SET
  name = 'BITSAT',
  short_name = 'BITSAT',
  full_name = 'BITS Admission Test 2026',
  category = 'Engineering',
  categories = ARRAY['Engineering', 'Pharmacy', 'Science'],
  level = 'Undergraduate',
  exam_type = 'University entrance exam',
  mode = 'Computer-based test',
  frequency = 'Two sessions in 2026',
  duration = '3 hours',
  language = 'English',
  application_mode = 'Online',
  application_start_date = '15 December 2025',
  application_end_date = '19 March 2026 for Session 1 or both sessions',
  exam_date = '15-17 April 2026 (Session 1); 25-27 May 2026 (Session 2)',
  status = 'Result Declared',
  official_website = 'https://admissions.bits-pilani.ac.in/',
  website = 'https://admissions.bits-pilani.ac.in/',
  brochure_url = 'https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf',
  registration_url = 'https://admissions.bits-pilani.ac.in/',
  eligibility = 'Applicants had to be appearing for Class 12 in 2026 or have passed in 2025. Programme-specific subject rules applied. The official brochure required 75% aggregate in PCM or PCB, as relevant, with at least 60% in each required subject.',
  description = 'BITSAT 2026 was BITS Pilani’s computer-based admission test for Integrated First Degree programmes at the Pilani, Goa and Hyderabad campuses.',
  page_summary = 'BITSAT 2026 offered two test sessions. The three-hour paper contained 130 objective questions across Physics, Chemistry, English proficiency, logical reasoning, and Mathematics or Biology.',
  summary_content = '<h2>What was BITSAT 2026?</h2><p>BITSAT was the admission test for Integrated First Degree programmes across the three main BITS Pilani campuses. Students could appear in both sessions, with the higher moderated score considered under the official rules.</p><p>The test rewarded speed and accuracy, but it also allowed candidates who completed all 130 questions to attempt up to 12 additional questions.</p>',
  application_process = '<h2>How to apply</h2><ol><li>Complete the BITSAT application on the official BITS admission portal.</li><li>Select Session 1, Session 2 or both, and pay the applicable fee.</li><li>Use the announced window to edit allowed details and reserve a test date and slot.</li><li>Download the hall ticket and later submit Class 12 marks and programme preferences for admission consideration.</li></ol>',
  exam_pattern = 'The three-hour computer-based test had 130 objective questions. A correct answer earned 3 marks, an incorrect answer lost 1 mark and an unanswered question earned 0. Candidates who answered all 130 questions could choose to attempt up to 12 extra questions.',
  dates_content = '<h2>BITSAT 2026 timeline</h2><ul><li>Applications opened on 15 December 2025.</li><li>The Session 1 or both-sessions application deadline was 19 March 2026.</li><li>Session 1 was held from 15 to 17 April 2026.</li><li>Session 2 was held from 25 to 27 May 2026.</li><li>The Class 12 marks and preference process followed through the official admission portal.</li></ul>',
  result_content = '<h2>BITSAT 2026 score</h2><p>Candidates received a test score after their session, followed by the official moderated score process. Admission depended on the final score, Class 12 eligibility and the programme preference and iteration process-not the test score alone.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Application Start','date','15 December 2025'),
    jsonb_build_object('event','Session 1/Both Sessions Deadline','date','19 March 2026'),
    jsonb_build_object('event','Session 1','date','15-17 April 2026'),
    jsonb_build_object('event','Session 2','date','25-27 May 2026'),
    jsonb_build_object('event','Session 2 Final Score','date','5 June 2026')
  ),
  meta_title = 'BITSAT 2026: Official Dates, Eligibility, Pattern and Score',
  meta_description = 'Check BITSAT 2026 official session dates, eligibility, 130-question test pattern, marking scheme, score process and BITS admission steps.',
  meta_keywords = 'BITSAT 2026, BITSAT result, BITSAT dates, BITSAT eligibility, BITSAT pattern, BITS Pilani admission',
  data_source_urls = jsonb_build_array(
    'https://admissions.bits-pilani.ac.in/',
    'https://admissions.bits-pilani.ac.in/FD/FD_brochure.html',
    'https://admissions.bits-pilani.ac.in/FD/downloads/BITSAT-2026_brochure.pdf'
  ),
  data_verified_at = now(),
  data_last_checked_at = now(),
  data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned',
  updated_at = now()
WHERE slug = 'bitsat-2026';

UPDATE public.exams
SET
  name = 'XAT',
  short_name = 'XAT',
  full_name = 'Xavier Aptitude Test 2026',
  category = 'Management',
  categories = ARRAY['Management'],
  level = 'Postgraduate',
  exam_type = 'Management entrance exam',
  mode = 'Computer-based test',
  frequency = 'Annual',
  language = 'English',
  application_mode = 'Online',
  application_start_date = '10 July 2025',
  application_end_date = '5 December 2025',
  exam_date = '4 January 2026',
  result_date = 'Last week of January 2026',
  status = 'Result Declared',
  official_website = 'https://xatonline.in/',
  website = 'https://xatonline.in/',
  brochure_url = 'https://xatonline.in/assets/pdf/XAT-e_Bulletin-2026.pdf',
  registration_url = 'https://xatonline.in/',
  eligibility = 'Candidates holding a recognised bachelor’s degree of at least three years, or completing their final examination by the deadline stated in the official bulletin, could apply. Individual participating institutes could have additional admission conditions.',
  description = 'XAT 2026 was the national management entrance test administered for XLRI programmes and other participating business schools that accepted XAT scores.',
  page_summary = 'XAT 2026 was held on Sunday, 4 January 2026. The official cycle covered registration, admit card, the computer-based test, score card and institute-specific selection stages.',
  summary_content = '<h2>What was XAT 2026?</h2><p>XAT was a management aptitude test used by XLRI and many participating institutes. A XAT score did not itself guarantee admission; shortlisted candidates still followed each institute’s selection process.</p><p>Students should distinguish between registering for the XAT exam and separately applying to programmes or institutes that use the score.</p>',
  application_process = '<h2>How the application worked</h2><ol><li>Register on the official portal and retain the generated XAT ID.</li><li>Complete academic and personal details and upload the required photograph and signature.</li><li>Select applicable XLRI programmes where required and pay the prescribed fee.</li><li>Use the same portal for admit-card and score-card access.</li></ol>',
  dates_content = '<h2>XAT 2026 timeline</h2><ul><li>Registration ran from 10 July to 5 December 2025.</li><li>The admit card was scheduled from 20 December 2025.</li><li>The examination was held on 4 January 2026.</li><li>The result was scheduled for the last week of January 2026.</li><li>Score-card download was scheduled from 31 January to 31 March 2026.</li></ul>',
  result_content = '<h2>XAT 2026 result</h2><p>Candidates accessed the result and score card through the official XAT login. Participating institutes then used their own cut-offs and selection stages, which could include interviews, group exercises, written tasks or other assessments.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Registration Start','date','10 July 2025'),
    jsonb_build_object('event','Registration End','date','5 December 2025'),
    jsonb_build_object('event','Admit Card','date','From 20 December 2025 (tentative)'),
    jsonb_build_object('event','Exam Date','date','4 January 2026'),
    jsonb_build_object('event','Result','date','Last week of January 2026'),
    jsonb_build_object('event','Score Card Window','date','31 January-31 March 2026')
  ),
  meta_title = 'XAT 2026: Official Dates, Eligibility, Result and Score Card',
  meta_description = 'Review XAT 2026 official registration and exam dates, eligibility, score-card window, XLRI application context and admission next steps.',
  meta_keywords = 'XAT 2026, XAT result, XAT dates, XAT eligibility, XAT score card, XLRI admission',
  data_source_urls = jsonb_build_array(
    'https://xatonline.in/',
    'https://xatonline.in/assets/pdf/XAT-e_Bulletin-2026.pdf'
  ),
  data_verified_at = now(),
  data_last_checked_at = now(),
  data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned',
  updated_at = now()
WHERE slug = 'xat-2026';

UPDATE public.exams
SET
  name = 'NEET UG',
  short_name = 'NEET UG',
  full_name = 'National Eligibility cum Entrance Test (Undergraduate) 2026',
  category = 'Medical',
  categories = ARRAY['Medical', 'Dental', 'AYUSH'],
  level = 'Undergraduate',
  exam_type = 'National medical entrance exam',
  mode = 'Pen-and-paper test',
  frequency = 'Annual',
  duration = '3 hours',
  application_mode = 'Online',
  application_end_date = '8 March 2026',
  exam_date = '3 May 2026; official re-examination held on 21 June 2026',
  result_date = '21 June 2026 re-examination result released',
  status = 'Result Declared',
  official_website = 'https://neet.nta.nic.in/',
  website = 'https://neet.nta.nic.in/',
  brochure_url = 'https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/02/202602231394640855.pdf',
  registration_url = 'https://neet.nta.nic.in/',
  eligibility = 'Applicants had to meet the qualifying-examination and subject requirements in the official bulletin. Candidates also had to complete 17 years of age by 31 December 2026. The bulletin did not prescribe an upper age limit.',
  description = 'NEET UG 2026 was the common national entrance examination for undergraduate medical education and specified dental, AYUSH and homoeopathy programmes.',
  page_summary = 'NEET UG 2026 used a three-hour pen-and-paper format with 180 compulsory questions in Physics, Chemistry and Biology. NTA later conducted an official re-examination on 21 June 2026.',
  summary_content = '<h2>What happened in NEET UG 2026?</h2><p>NEET UG remained the common medical entrance examination for undergraduate admissions covered by the official bulletin. The main examination took place on 3 May 2026, after which NTA announced a re-examination for the affected 2026 cycle on 21 June.</p><p>Because the cycle included refund, re-examination and revised result notices, candidates should use the official NTA portal for their own score card and candidate-specific status.</p>',
  application_process = '<h2>How the application worked</h2><ol><li>Register on the official NEET portal and complete identity and contact verification.</li><li>Enter academic, category and exam-centre information.</li><li>Upload the required documents, pay the fee and save the confirmation page.</li><li>Use NTA candidate services for correction, city intimation, admit card, response sheet and score card.</li></ol>',
  exam_pattern = 'The pen-and-paper test contained 180 compulsory questions: 45 Physics, 45 Chemistry and 90 Biology questions, for 720 marks. Correct answers received 4 marks, incorrect answers lost 1 mark and unanswered questions received 0.',
  dates_content = '<h2>NEET UG 2026 timeline</h2><ul><li>The extended application deadline was 8 March 2026.</li><li>The original examination was conducted on 3 May 2026.</li><li>NTA conducted the official re-examination on 21 June 2026.</li><li>Final answer keys, result and score-card services were published through the official portal.</li></ul>',
  result_content = '<h2>NEET UG 2026 result</h2><p>NTA published the re-examination final answer key, result press release and score-card links on the official website. Qualified candidates still needed to follow MCC, state or institution-specific counselling as applicable.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Extended Application Deadline','date','8 March 2026'),
    jsonb_build_object('event','Original Exam','date','3 May 2026'),
    jsonb_build_object('event','Official Re-examination','date','21 June 2026'),
    jsonb_build_object('event','Re-examination Result','date','Released')
  ),
  meta_title = 'NEET UG 2026: Official Dates, Re-exam, Pattern and Result',
  meta_description = 'Check NEET UG 2026 official exam and re-exam dates, eligibility, 180-question pattern, result and score-card guidance from NTA sources.',
  meta_keywords = 'NEET UG 2026, NEET result, NEET re-exam 2026, NEET eligibility, NEET pattern, NTA NEET',
  data_source_urls = jsonb_build_array(
    'https://neet.nta.nic.in/',
    'https://cdnbbsr.s3waas.gov.in/s37bc1ec1d9c3426357e69acd5bf320061/uploads/2026/02/202602231394640855.pdf',
    'https://neet.nta.nic.in/document/list-of-toppers-of-neetug-2026-held-on-21st-june-2026/'
  ),
  data_verified_at = now(),
  data_last_checked_at = now(),
  data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned',
  updated_at = now()
WHERE slug IN ('neet-ug-2026', 'national-eligibility-cum-entrance-test-neet');
