-- Direct, source-backed 2026 exam curation: batch 03.
-- Duplicate legacy slugs are intentionally synchronised to prevent conflicting pages.

UPDATE public.exams
SET
  name = 'GATE',
  short_name = 'GATE',
  full_name = 'Graduate Aptitude Test in Engineering 2026',
  category = 'Engineering',
  categories = ARRAY['Engineering', 'Technology', 'Science', 'Architecture', 'Humanities'],
  level = 'Postgraduate',
  exam_type = 'National-level aptitude examination',
  mode = 'Computer-based test',
  frequency = 'Annual',
  duration = '3 hours',
  language = 'English',
  application_mode = 'Online',
  application_start_date = '28 August 2025',
  application_end_date = '7 October 2025 without late fee; 13 October 2025 with late fee',
  exam_date = '7, 8, 14 and 15 February 2026',
  result_date = '19 March 2026',
  status = 'Result Declared',
  official_website = 'https://gate2026.iitg.ac.in/',
  website = 'https://gate2026.iitg.ac.in/',
  brochure_url = 'https://gate2026.iitg.ac.in/doc/IB/GATE2026-IB-v21082025-1800.pdf',
  registration_url = 'https://goaps.iitg.ac.in/',
  eligibility = 'Students in the third or a higher year of an approved undergraduate programme, or graduates of an approved programme in Engineering, Technology, Architecture, Science, Commerce, Arts or Humanities, could appear. There was no age limit.',
  description = 'GATE 2026 was organised by IIT Guwahati on behalf of the national GATE committee. It assessed undergraduate-level subject understanding for postgraduate admission, possible financial assistance and selected recruitment processes.',
  page_summary = 'GATE 2026 covered 30 test papers and allowed eligible candidates to take one or an approved combination of two papers. Results were announced on 19 March 2026 and scores remain valid for three years.',
  summary_content = '<h2>What was GATE 2026?</h2><p>GATE 2026 was more than an engineering entrance test. Its paper list included disciplines across engineering, technology, science, architecture, commerce, arts and humanities. A valid score could support postgraduate applications and selected recruitment processes, subject to each organisation’s rules.</p><p>Qualifying did not automatically secure admission, financial assistance or a PSU position. Candidates still had to meet the requirements of the institute or employer receiving the score.</p>',
  application_process = '<h2>How the GATE application worked</h2><ol><li>Register through GOAPS and create a candidate account.</li><li>Select the test paper and preferred examination cities.</li><li>Enter academic details and upload the required photograph, signature and supporting documents.</li><li>Pay the fee, submit the form and later use GOAPS for the admit card, result and score card.</li></ol>',
  exam_pattern = 'GATE 2026 was a three-hour computer-based test. Paper structure varied by discipline and included General Aptitude plus subject-specific questions. Question types included MCQ, MSQ and numerical-answer questions, with negative marking applying only where specified.',
  dates_content = '<h2>GATE 2026 timeline</h2><ul><li>Registration opened on 28 August 2025.</li><li>The regular application deadline was extended to 7 October 2025.</li><li>The late-fee deadline was 13 October 2025.</li><li>Admit cards became available on 13 January 2026.</li><li>Exams were held on 7, 8, 14 and 15 February 2026.</li><li>Results were announced on 19 March 2026.</li></ul>',
  result_content = '<h2>GATE 2026 result and score card</h2><p>Results and score cards were released through GOAPS. The score remains valid for three years from the result date, although every institute, scholarship route and employer applies its own eligibility and selection conditions.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Registration Start','date','28 August 2025'),
    jsonb_build_object('event','Regular Deadline','date','7 October 2025'),
    jsonb_build_object('event','Late-Fee Deadline','date','13 October 2025'),
    jsonb_build_object('event','Admit Card','date','13 January 2026'),
    jsonb_build_object('event','Exam Dates','date','7, 8, 14 and 15 February 2026'),
    jsonb_build_object('event','Result','date','19 March 2026')
  ),
  meta_title = 'GATE 2026: Official Dates, Eligibility, Result and Score Card',
  meta_description = 'Review GATE 2026 official dates, broad eligibility, paper format, result, score-card validity and postgraduate admission context.',
  meta_keywords = 'GATE 2026, GATE result 2026, GATE dates, GATE eligibility, GATE score card, IIT Guwahati GATE',
  data_source_urls = jsonb_build_array(
    'https://gate2026.iitg.ac.in/',
    'https://gate2026.iitg.ac.in/important-dates.html',
    'https://gate2026.iitg.ac.in/eligibility-criteria.html',
    'https://gate2026.iitg.ac.in/doc/IB/GATE2026-IB-v21082025-1800.pdf'
  ),
  data_verified_at = now(), data_last_checked_at = now(), data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned', updated_at = now()
WHERE slug IN ('gate-2026', 'gate');

UPDATE public.exams
SET
  name = 'CEED',
  short_name = 'CEED',
  full_name = 'Common Entrance Examination for Design 2026',
  category = 'Design',
  categories = ARRAY['Design'],
  level = 'Postgraduate',
  exam_type = 'Design aptitude examination',
  mode = 'Computer-based Part A and drawing/writing Part B',
  frequency = 'Annual',
  duration = '3 hours',
  language = 'English',
  application_mode = 'Online',
  application_start_date = '1 October 2025',
  application_end_date = '5 November 2025 with regular fee; 10 November 2025, 5:00 PM with late fee',
  exam_date = '18 January 2026, 9:00 AM to 12:00 noon',
  result_date = '4 March 2026',
  status = 'Result Declared',
  official_website = 'https://www.ceed.iitb.ac.in/2026/',
  website = 'https://www.ceed.iitb.ac.in/2026/',
  brochure_url = 'https://www.ceed.iitb.ac.in/2026/downloads/CEED2026_Brochure.pdf',
  registration_url = 'https://www.ceed.iitb.ac.in/2026/',
  eligibility = 'Applicants had to complete a degree, diploma or postgraduate programme of at least three years after Class 12, be appearing in its final examination by July 2026, or complete a 10+5 GD Arts diploma by July 2026. CEED had no age limit or attempt limit.',
  description = 'CEED 2026 was IIT Bombay’s design aptitude examination for MDes and selected PhD admission pathways. Participating institutes could use the score alongside their own eligibility checks, tests or interviews.',
  page_summary = 'CEED 2026 was held on 18 January 2026. Part A tested objective design aptitude on a computer, while Part B assessed drawing, creativity, visual sensitivity and problem identification.',
  summary_content = '<h2>What was CEED 2026?</h2><p>CEED measured how candidates observed, reasoned, communicated and solved design problems. Part A acted as the shortlisting stage, while Part B gave greater weight to hands-on design, drawing and written responses.</p><p>A CEED rank was not an automatic admission offer. Qualified students had to apply separately to participating institutes and complete their programme-specific selection process.</p>',
  application_process = '<h2>How the application worked</h2><ol><li>Register only through the official CEED website.</li><li>Upload the prescribed photograph, signature, qualifying-degree proof and relevant category or disability certificates.</li><li>Pay the online registration fee and retain the submitted form.</li><li>Use the candidate portal for the admit card, answer-key comments, result and score card.</li></ol>',
  exam_pattern = 'Part A lasted one hour and contained NAT, MSQ and MCQ questions on computer. Part B lasted two hours and contained five mandatory design, drawing and writing questions answered in the supplied booklet. The final score used 25% of Part A and 75% of Part B.',
  dates_content = '<h2>CEED 2026 timeline</h2><ul><li>Registration opened on 1 October 2025.</li><li>The extended regular-fee deadline was 5 November 2025, followed by a late-fee deadline on 10 November.</li><li>The exam was held on 18 January 2026.</li><li>The final Part A answer key was released on 29 January 2026.</li><li>Results were released on 4 March 2026.</li><li>Score cards were downloadable from 10 March to 31 July 2026.</li></ul>',
  result_content = '<h2>CEED 2026 result</h2><p>Results were released on 4 March 2026 and score cards became available from 10 March. The CEED 2026 score remains valid for one year from the result declaration date.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Registration Start','date','1 October 2025'),
    jsonb_build_object('event','Extended Regular Deadline','date','5 November 2025'),
    jsonb_build_object('event','Late-Fee Deadline','date','10 November 2025, 5:00 PM'),
    jsonb_build_object('event','Exam','date','18 January 2026'),
    jsonb_build_object('event','Result','date','4 March 2026'),
    jsonb_build_object('event','Score Card Window','date','10 March-31 July 2026')
  ),
  meta_title = 'CEED 2026: Official Dates, Eligibility, Pattern and Result',
  meta_description = 'Understand CEED 2026 official dates, eligibility, Part A and Part B format, result, score-card validity and MDes admission steps.',
  meta_keywords = 'CEED 2026, CEED result, CEED dates, CEED eligibility, CEED pattern, MDes admission',
  data_source_urls = jsonb_build_array(
    'https://www.ceed.iitb.ac.in/2026/',
    'https://www.ceed.iitb.ac.in/2026/downloads/CEED2026_Brochure.pdf'
  ),
  data_verified_at = now(), data_last_checked_at = now(), data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned', updated_at = now()
WHERE slug IN ('ceed', 'CEED');

UPDATE public.exams
SET
  name = 'CLAT',
  short_name = 'CLAT',
  full_name = 'Common Law Admission Test 2026',
  category = 'Law',
  categories = ARRAY['Law'],
  level = 'Undergraduate and Postgraduate',
  exam_type = 'National law admission test',
  mode = 'Offline pen-and-paper examination',
  frequency = 'Annual',
  duration = '2 hours',
  language = 'English',
  application_mode = 'Online',
  exam_date = '7 December 2025, 2:00 PM to 4:00 PM',
  status = 'Counselling',
  official_website = 'https://consortiumofnlus.ac.in/clat-2026/',
  website = 'https://consortiumofnlus.ac.in/clat-2026/',
  registration_url = 'https://consortiumofnlus.ac.in/clat-2026/',
  eligibility = 'For CLAT UG, applicants needed Class 12 or equivalent with at least 45% marks, or 40% for SC, ST and PwD candidates. Students appearing in March or April 2026 could also apply, subject to producing proof at admission. There was no upper age limit.',
  description = 'CLAT 2026 was the offline common admission test for five-year integrated LL.B. and LL.M. programmes at participating National Law Universities for the 2026-27 academic year.',
  page_summary = 'CLAT 2026 was held on 7 December 2025. The UG paper had 120 one-mark questions across English, current affairs, legal reasoning, logical reasoning and quantitative techniques.',
  summary_content = '<h2>What was CLAT 2026?</h2><p>CLAT was the shared admission route used by participating National Law Universities. UG and PG candidates took the examination during the same notified window but followed separate eligibility, syllabus and counselling requirements.</p><p>A CLAT rank entered the candidate into the consortium counselling process; individual NLU reservation, document and admission rules still applied.</p>',
  application_process = '<h2>How the application worked</h2><ol><li>Register online through the Consortium of NLUs website.</li><li>Select the UG or PG programme and complete personal, academic and reservation details.</li><li>Upload the required documents, choose NLU preferences where enabled and pay the fee.</li><li>Use the candidate login for the admit card, result and counselling steps.</li></ol>',
  exam_pattern = 'The CLAT UG paper had 120 multiple-choice questions for 120 marks and a two-hour duration. Each wrong answer attracted a 0.25-mark penalty. The five sections were English, Current Affairs including General Knowledge, Legal Reasoning, Logical Reasoning and Quantitative Techniques.',
  dates_content = '<h2>CLAT 2026 timeline</h2><ul><li>The examination was scheduled for Sunday, 7 December 2025.</li><li>The standard test time was 2:00 PM to 4:00 PM.</li><li>Eligible PwD candidates received the separately notified extended duration.</li><li>Admission counselling followed through the Consortium portal for the 2026-27 academic year.</li></ul>',
  result_content = '<h2>CLAT 2026 result and counselling</h2><p>Candidates used their Consortium login for the result and counselling process. Seat allocation depended on rank, NLU preferences, reservation rules, document verification and payment within each notified round.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Exam Date','date','7 December 2025'),
    jsonb_build_object('event','Exam Time','date','2:00 PM-4:00 PM'),
    jsonb_build_object('event','Academic Session','date','2026-27')
  ),
  meta_title = 'CLAT 2026: Eligibility, Exam Pattern, Result and Counselling',
  meta_description = 'Review CLAT 2026 official UG eligibility, offline exam format, marking scheme, result context and Consortium counselling steps.',
  meta_keywords = 'CLAT 2026, CLAT result, CLAT eligibility, CLAT pattern, CLAT counselling, NLU admission',
  data_source_urls = jsonb_build_array(
    'https://consortiumofnlus.ac.in/clat-2026/',
    'https://consortiumofnlus.ac.in/clat-2026/ug-instructions.html',
    'https://consortiumofnlus.ac.in/clat-2026/ug-eligibility.html',
    'https://consortiumofnlus.ac.in/clat-2026/ug-question-format.html'
  ),
  data_verified_at = now(), data_last_checked_at = now(), data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned', updated_at = now()
WHERE slug IN ('clat', 'clat-2026');

UPDATE public.exams
SET
  name = 'COMEDK UGET',
  short_name = 'COMEDK UGET',
  full_name = 'COMEDK Undergraduate Entrance Test 2026',
  category = 'Engineering',
  categories = ARRAY['Engineering'],
  level = 'Undergraduate',
  exam_type = 'Private engineering entrance test',
  mode = 'Computer-based test',
  frequency = 'Annual',
  language = 'English',
  application_mode = 'Online',
  application_start_date = '3 February 2026, 2:00 PM',
  application_end_date = '23 March 2026, 4:00 PM after extensions',
  exam_date = '9 May 2026',
  result_date = '29 May 2026, 6:00 PM',
  status = 'Result Declared',
  official_website = 'https://www.comedk.org/',
  website = 'https://www.comedk.org/',
  registration_url = 'https://www.comedk.org/',
  eligibility = 'Applicants needed a recognised second PUC or Class 12 equivalent with Physics, Mathematics and English, plus an allowed optional subject. General Merit candidates required 45% aggregate in Physics, Chemistry and Mathematics; Karnataka SC, ST and OBC candidates required 40%. Diploma candidates were not eligible for B.E./B.Tech lateral entry through this test.',
  description = 'COMEDK UGET 2026 was the computer-based entrance test used for engineering seat selection in participating private colleges in Karnataka, followed by centralised online counselling.',
  page_summary = 'COMEDK UGET and Uni-GAUGE E were held as one combined examination on 9 May 2026. Rank and score cards became available through candidate login on 29 May.',
  summary_content = '<h2>What was COMEDK UGET 2026?</h2><p>COMEDK UGET gave eligible students across India a route to participating Karnataka engineering colleges. The exam was combined with Uni-GAUGE E on the same day, but their score use and counselling processes remained separate.</p><p>COMEDK candidates followed centralised online counselling, while Uni-GAUGE candidates applied directly to participating universities.</p>',
  application_process = '<h2>How the application worked</h2><ol><li>Register through the official COMEDK website and create login credentials.</li><li>Complete the online form, upload the required documents and pay through the available gateway.</li><li>Use the limited correction window for eligible fields.</li><li>Download the Test Admission Ticket and later access the rank card through candidate login.</li></ol>',
  dates_content = '<h2>COMEDK UGET 2026 timeline</h2><ul><li>Applications opened on 3 February 2026 at 2:00 PM.</li><li>The extended deadline was 23 March 2026 at 4:00 PM.</li><li>The exam was held on 9 May 2026.</li><li>Final answer keys were published on 23 May 2026.</li><li>Rank and score cards went live on 29 May 2026 at 6:00 PM.</li></ul>',
  result_content = '<h2>COMEDK UGET 2026 rank card</h2><p>Eligible candidates downloaded the rank card from their applicant login. COMEDK engineering seat selection then proceeded through the separately published online counselling schedule.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Application Start','date','3 February 2026, 2:00 PM'),
    jsonb_build_object('event','Extended Deadline','date','23 March 2026, 4:00 PM'),
    jsonb_build_object('event','Exam','date','9 May 2026'),
    jsonb_build_object('event','Final Answer Key','date','23 May 2026, 2:00 PM'),
    jsonb_build_object('event','Rank/Score Card','date','29 May 2026, 6:00 PM')
  ),
  meta_title = 'COMEDK UGET 2026: Dates, Eligibility, Result and Counselling',
  meta_description = 'Check COMEDK UGET 2026 official dates, engineering eligibility, exam and rank-card timeline, and online counselling context.',
  meta_keywords = 'COMEDK UGET 2026, COMEDK result, COMEDK dates, COMEDK eligibility, COMEDK rank card, engineering counselling',
  data_source_urls = jsonb_build_array(
    'https://www.comedk.org/',
    'https://www.comedk.org/index.php/about-uget-and-notification-2026'
  ),
  data_verified_at = now(), data_last_checked_at = now(), data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned', updated_at = now()
WHERE slug IN ('comedk', 'comedk-uget');

UPDATE public.exams
SET
  name = 'AP EAPCET',
  short_name = 'AP EAPCET',
  full_name = 'Andhra Pradesh Engineering, Agriculture and Pharmacy Common Entrance Test 2026',
  category = 'Engineering',
  categories = ARRAY['Engineering', 'Agriculture', 'Pharmacy'],
  level = 'Undergraduate',
  exam_type = 'State entrance test',
  mode = 'Computer-based test',
  frequency = 'Annual',
  application_mode = 'Online',
  application_start_date = '4 February 2026',
  application_end_date = '24 March 2026 without late fee',
  exam_date = '12-18 May 2026 for Engineering; 19-20 May 2026 for Agriculture and Pharmacy',
  status = 'Answer Key Released',
  official_website = 'https://cets.apsche.ap.gov.in/EAPCET/',
  website = 'https://cets.apsche.ap.gov.in/EAPCET/',
  registration_url = 'https://cets.apsche.ap.gov.in/EAPCET/',
  description = 'AP EAPCET 2026 was conducted by JNTU Kakinada on behalf of APSCHE for undergraduate engineering, agriculture and pharmacy admission pathways in Andhra Pradesh.',
  page_summary = 'AP EAPCET 2026 engineering sessions ran from 12 to 18 May, followed by agriculture and pharmacy sessions on 19 and 20 May. Preliminary keys were released on 25 May.',
  summary_content = '<h2>What was AP EAPCET 2026?</h2><p>AP EAPCET was the state entrance test for several professional undergraduate pathways in Andhra Pradesh. Engineering and Agriculture/Pharmacy candidates followed separate examination sessions and official syllabus links.</p><p>At the time of this verification, APSCHE had released preliminary keys and said the result schedule would be updated after the relevant Intermediate result process.</p>',
  application_process = '<h2>How the application worked</h2><ol><li>Pay the application fee through the official APSCHE portal.</li><li>Use the payment reference to complete the online application.</li><li>Check the submitted form and use the correction window for permitted details.</li><li>Download the hall ticket and later use official services for keys, objections and results.</li></ol>',
  dates_content = '<h2>AP EAPCET 2026 timeline</h2><ul><li>The notification was issued on 3 February 2026 and applications opened on 4 February.</li><li>The no-late-fee deadline was 24 March 2026.</li><li>Engineering exams ran from 12 to 15 May and again on 18 May.</li><li>Agriculture and Pharmacy exams were held on 19 and 20 May.</li><li>Preliminary keys were released on 25 May at 11:00 AM.</li></ul>',
  result_content = '<h2>AP EAPCET 2026 result status</h2><p>The official portal stated that results would be announced after the relevant Intermediate betterment and advanced supplementary results. Candidates should rely on APSCHE candidate services for the final rank card and counselling notice.</p>',
  important_dates = jsonb_build_array(
    jsonb_build_object('event','Notification','date','3 February 2026'),
    jsonb_build_object('event','Application Start','date','4 February 2026'),
    jsonb_build_object('event','No-Late-Fee Deadline','date','24 March 2026'),
    jsonb_build_object('event','Engineering Exams','date','12-18 May 2026'),
    jsonb_build_object('event','Agriculture/Pharmacy Exams','date','19-20 May 2026'),
    jsonb_build_object('event','Preliminary Key','date','25 May 2026, 11:00 AM')
  ),
  meta_title = 'AP EAPCET 2026: Official Dates, Keys and Result Status',
  meta_description = 'Review AP EAPCET 2026 official application dates, engineering and agriculture/pharmacy exam windows, preliminary keys and current result status.',
  meta_keywords = 'AP EAPCET 2026, AP EAMCET 2026, AP EAPCET result, AP EAPCET dates, AP EAPCET answer key',
  data_source_urls = jsonb_build_array(
    'https://cets.apsche.ap.gov.in/EAPCET/',
    'https://cets.apsche.ap.gov.in/Eapcet/EapcetHomePages/ImportantDates',
    'https://cets.apsche.ap.gov.in/eapcet/eapcet/eapcet_exampapers.aspx'
  ),
  data_verified_at = now(), data_last_checked_at = now(), data_quality_score = 100,
  data_clean_attempts = greatest(coalesce(data_clean_attempts, 0) + 1, 1),
  data_clean_successes = greatest(coalesce(data_clean_successes, 0) + 1, 1),
  data_clean_state = 'cleaned', updated_at = now()
WHERE slug IN ('ap-eapcet', 'ap-eamcet');
