-- Top popular careers refresh for 2026.
-- Intent: add high-demand career profiles with no image dependency so the site uses
-- the existing professional fallback avatar. Content is structured for AIO, AEO,
-- SEO, GEO and LLMO with answer-first summaries, descriptive headings and
-- internal entity links.

UPDATE public.career_profiles
SET image = ''
WHERE COALESCE(image, '') <> '';

WITH careers(slug, name, domain, short_description, description, page_summary, avg_salary, growth, experience_required, top_skills, top_companies, related_courses, related_exams, job_roles, icon_emoji, meta_title, meta_description, meta_keywords, is_featured, display_order) AS (
  VALUES
  (
    'ai-ml-engineer',
    'AI and Machine Learning Engineer',
    'Artificial Intelligence',
    'AI and Machine Learning Engineers build models, agents and automation systems that help products make smarter decisions.',
    $career$<h2>What does an AI and Machine Learning Engineer do?</h2><p>An AI and Machine Learning Engineer designs, trains, evaluates and ships intelligent systems. The role is popular in 2026 because companies are adding AI copilots, recommendation engines, fraud models, vision systems and workflow automation to real products.</p><h2>Best-fit students</h2><p>This career suits students who enjoy mathematics, coding, experiments and practical problem solving. A strong path usually starts with <a href="/courses/btech">B.Tech</a>, <a href="/courses/bca">BCA</a>, <a href="/courses/mca">MCA</a> or a data science focused postgraduate course.</p><h2>Skills to build first</h2><p>Start with Python, statistics, linear algebra, SQL, model evaluation, prompt engineering, MLOps basics and responsible AI. Build projects that solve visible problems instead of only copying notebooks.</p><h2>Career outlook</h2><p>Demand is strong across product companies, banks, health-tech, edtech, logistics and consulting. Entry roles may begin as machine learning engineer, AI engineer, NLP engineer, computer vision engineer or applied scientist.</p><h2>FAQ</h2><h3>Is AI engineering good for freshers?</h3><p>Yes, if the fresher has real projects, coding strength and an ability to explain model choices clearly.</p><h3>Which course is useful?</h3><p>Computer science, data science, statistics and electronics routes can all work when backed by practical AI projects.</p>$career$,
    'AI and Machine Learning Engineer is a high-growth technology career for students who want to build intelligent products, agents and automation systems. Focus on Python, statistics, model evaluation, MLOps and responsible AI projects.',
    '₹8 - 35 LPA',
    'Very High',
    '0 - 2 years for junior roles; 3+ years for production ML ownership',
    ARRAY['Python','Machine Learning','Deep Learning','Statistics','MLOps','Prompt Engineering','Model Evaluation'],
    ARRAY['Google','Microsoft','Amazon','TCS','Infosys','Fractal','Razorpay','Flipkart'],
    ARRAY['btech','bca','mca','msc'],
    ARRAY['jee-main','gate','cuet'],
    '[{"title":"AI Engineer","level":"Entry to Mid"},{"title":"Machine Learning Engineer","level":"Entry to Senior"},{"title":"NLP Engineer","level":"Mid"},{"title":"Computer Vision Engineer","level":"Mid"}]'::jsonb,
    '🤖',
    'AI and Machine Learning Engineer Career Scope 2026',
    'Explore AI and Machine Learning Engineer salary, skills, courses, exams, job roles and career scope for Indian students in 2026.',
    'AI engineer career, machine learning engineer, AI jobs India, ML engineer salary, AI courses',
    true,
    1
  ),
  (
    'data-scientist',
    'Data Scientist',
    'Data and Analytics',
    'Data Scientists turn raw data into decisions, forecasts and measurable business insight.',
    $career$<h2>What does a Data Scientist do?</h2><p>A Data Scientist combines statistics, business understanding and programming to answer important questions with data. In 2026, this remains one of the most searched career paths because almost every sector now needs evidence-based decisions.</p><h2>Best-fit students</h2><p>This path fits students who like numbers, patterns, dashboards and asking why something is happening. Common routes include <a href="/courses/btech">B.Tech</a>, <a href="/courses/bca">BCA</a>, <a href="/courses/mca">MCA</a>, <a href="/courses/msc">M.Sc</a>, economics, statistics and analytics programmes.</p><h2>Skills to build first</h2><p>Learn SQL, Python, statistics, Excel, data cleaning, visualisation, experimentation and storytelling. A good portfolio should include end-to-end projects with a clear question, method and conclusion.</p><h2>Career outlook</h2><p>Hiring is strong in fintech, ecommerce, SaaS, consulting, healthcare, telecom and consumer internet. Early roles include data analyst, business analyst, decision scientist and junior data scientist.</p><h2>FAQ</h2><h3>Is coding compulsory?</h3><p>Yes, at least SQL and Python are important for serious data roles.</p><h3>Can commerce students enter data science?</h3><p>Yes. Commerce students with statistics, analytics and finance context can become strong business-facing data professionals.</p>$career$,
    'Data Scientist is a strong career for students who like statistics, SQL, Python and business problem solving. It connects well with technology, commerce, economics and management routes.',
    '₹6 - 30 LPA',
    'Very High',
    '0 - 2 years for analyst roles; 2+ years for data scientist roles',
    ARRAY['SQL','Python','Statistics','Power BI','Machine Learning','Data Storytelling','Experimentation'],
    ARRAY['Google','Amazon','Flipkart','Zomato','Deloitte','Mu Sigma','Fractal','Accenture'],
    ARRAY['btech','bca','mca','msc','mba','bcom'],
    ARRAY['cuet','gate','cat'],
    '[{"title":"Data Analyst","level":"Entry"},{"title":"Business Analyst","level":"Entry"},{"title":"Data Scientist","level":"Mid"},{"title":"Decision Scientist","level":"Mid"}]'::jsonb,
    '📊',
    'Data Scientist Career Scope 2026 - Salary, Skills and Courses',
    'Explore Data Scientist career scope, salary, skills, courses, exams and top hiring sectors for Indian students.',
    'data scientist career, data analyst, analytics jobs, data science salary India',
    true,
    2
  ),
  (
    'cybersecurity-analyst',
    'Cybersecurity Analyst',
    'Cybersecurity',
    'Cybersecurity Analysts protect systems, users and data from attacks, fraud and digital risk.',
    $career$<h2>What does a Cybersecurity Analyst do?</h2><p>A Cybersecurity Analyst monitors threats, investigates incidents, improves security controls and helps organisations reduce digital risk. The role is highly relevant as payments, cloud systems, student data, hospital records and enterprise apps move online.</p><h2>Best-fit students</h2><p>This career suits students who enjoy networks, operating systems, ethical hacking, investigation and structured thinking. Good starting routes include <a href="/courses/btech">B.Tech</a>, <a href="/courses/bca">BCA</a> and <a href="/courses/mca">MCA</a>.</p><h2>Skills to build first</h2><p>Focus on networking, Linux, security operations, SIEM tools, web security, identity management, scripting and incident response. Ethical practice matters because this career works with sensitive systems.</p><h2>Career outlook</h2><p>Demand is strong in banks, IT services, cloud companies, government vendors, ecommerce and consulting. Entry roles include SOC analyst, security analyst, vulnerability analyst and GRC analyst.</p><h2>FAQ</h2><h3>Is cybersecurity only for hackers?</h3><p>No. It includes monitoring, compliance, cloud security, privacy, risk, audits and incident response.</p><h3>Which skill should I learn first?</h3><p>Networking and Linux are the best foundations before advanced tools.</p>$career$,
    'Cybersecurity Analyst is a high-demand career for students who want to protect digital systems. Start with networking, Linux, web security, SIEM basics and ethical incident response.',
    '₹5 - 24 LPA',
    'Very High',
    '0 - 2 years for SOC and junior analyst roles',
    ARRAY['Networking','Linux','SIEM','Incident Response','Web Security','Risk Assessment','Cloud Security'],
    ARRAY['Palo Alto Networks','Cisco','TCS','Wipro','Infosys','Deloitte','KPMG','EY'],
    ARRAY['btech','bca','mca'],
    ARRAY['jee-main','cuet'],
    '[{"title":"SOC Analyst","level":"Entry"},{"title":"Security Analyst","level":"Entry"},{"title":"Cloud Security Analyst","level":"Mid"},{"title":"GRC Analyst","level":"Entry to Mid"}]'::jsonb,
    '🛡️',
    'Cybersecurity Analyst Career Scope 2026',
    'Explore Cybersecurity Analyst salary, skills, courses, exams, job roles and career path in India.',
    'cybersecurity analyst, ethical hacking career, SOC analyst, cyber security jobs India',
    true,
    3
  ),
  (
    'cloud-devops-engineer',
    'Cloud and DevOps Engineer',
    'Cloud Computing',
    'Cloud and DevOps Engineers keep modern applications fast, reliable, secure and scalable.',
    $career$<h2>What does a Cloud and DevOps Engineer do?</h2><p>A Cloud and DevOps Engineer builds deployment pipelines, manages cloud infrastructure, improves reliability and supports engineering teams. This career is popular because startups, banks, SaaS companies and enterprise teams now run critical products on cloud platforms.</p><h2>Best-fit students</h2><p>This path suits students who enjoy systems, automation, debugging and reliability. <a href="/courses/btech">B.Tech</a>, <a href="/courses/bca">BCA</a> and <a href="/courses/mca">MCA</a> are practical routes.</p><h2>Skills to build first</h2><p>Learn Linux, networking, Git, Docker, Kubernetes, CI/CD, monitoring, cloud basics and infrastructure as code. Real deployment projects matter more than certificates alone.</p><h2>Career outlook</h2><p>Roles are available in product engineering, IT services, platform teams, fintech and ecommerce. Freshers can start with cloud support, DevOps trainee or site reliability associate roles.</p><h2>FAQ</h2><h3>Is DevOps only for experienced developers?</h3><p>No, but beginners need strong Linux, scripting and deployment practice.</p><h3>Which cloud should I learn?</h3><p>Any one major platform is fine at first. The concepts transfer across providers.</p>$career$,
    'Cloud and DevOps Engineer is a strong career for students who like systems, deployment, automation and reliability. Build Linux, Docker, Kubernetes, CI/CD and cloud portfolio projects.',
    '₹6 - 28 LPA',
    'Very High',
    '0 - 2 years for cloud support or DevOps trainee roles',
    ARRAY['Linux','Docker','Kubernetes','CI/CD','Cloud Platforms','Terraform','Monitoring'],
    ARRAY['Amazon Web Services','Microsoft','Google Cloud','TCS','Infosys','Zoho','Freshworks'],
    ARRAY['btech','bca','mca'],
    ARRAY['jee-main','gate','cuet'],
    '[{"title":"Cloud Engineer","level":"Entry"},{"title":"DevOps Engineer","level":"Entry to Mid"},{"title":"Site Reliability Engineer","level":"Mid"},{"title":"Platform Engineer","level":"Mid"}]'::jsonb,
    '☁️',
    'Cloud and DevOps Engineer Career Scope 2026',
    'Explore Cloud and DevOps Engineer salary, skills, courses, exams and job roles for Indian students.',
    'cloud engineer career, DevOps engineer, SRE jobs, cloud computing career India',
    true,
    4
  ),
  (
    'full-stack-developer',
    'Full Stack Developer',
    'Software Development',
    'Full Stack Developers build complete web and app products across frontend, backend and databases.',
    $career$<h2>What does a Full Stack Developer do?</h2><p>A Full Stack Developer builds user interfaces, backend APIs, databases and integrations. It remains one of the most practical career paths because every business needs usable digital products, internal tools and customer-facing platforms.</p><h2>Best-fit students</h2><p>This career suits students who like building visible products and learning by shipping. Strong routes include <a href="/courses/btech">B.Tech</a>, <a href="/courses/bca">BCA</a>, <a href="/courses/mca">MCA</a> and self-driven project learning.</p><h2>Skills to build first</h2><p>Learn HTML, CSS, JavaScript, React, Node.js, databases, APIs, authentication and deployment. A portfolio with 3 to 5 working projects can matter more than a long certificate list.</p><h2>Career outlook</h2><p>Hiring exists in startups, agencies, SaaS, ecommerce, edtech, fintech and IT services. Entry roles include frontend developer, backend developer and junior full stack developer.</p><h2>FAQ</h2><h3>Can I become a developer without a CSE degree?</h3><p>Yes, if your projects, problem-solving and coding discipline are strong.</p><h3>What should I build first?</h3><p>Build a complete app with login, database, search, admin panel and deployment.</p>$career$,
    'Full Stack Developer is a practical career for students who want to build complete digital products. Learn frontend, backend, databases, APIs and deployment with real projects.',
    '₹4 - 24 LPA',
    'High',
    '0 - 1 year for junior developer roles',
    ARRAY['JavaScript','React','Node.js','Databases','APIs','Git','Deployment'],
    ARRAY['Zoho','Freshworks','TCS','Infosys','Microsoft','Swiggy','Razorpay'],
    ARRAY['btech','bca','mca'],
    ARRAY['jee-main','cuet'],
    '[{"title":"Frontend Developer","level":"Entry"},{"title":"Backend Developer","level":"Entry"},{"title":"Full Stack Developer","level":"Entry to Mid"},{"title":"Software Engineer","level":"Entry to Senior"}]'::jsonb,
    '💻',
    'Full Stack Developer Career Scope 2026',
    'Explore Full Stack Developer salary, skills, courses, exams and job roles for Indian students.',
    'full stack developer career, web developer salary, software developer jobs India',
    true,
    5
  ),
  (
    'product-manager',
    'Product Manager',
    'Product and Business',
    'Product Managers decide what to build, why it matters and how teams should measure success.',
    $career$<h2>What does a Product Manager do?</h2><p>A Product Manager connects users, business goals, design, technology and data. The role is popular because digital companies need people who can turn customer problems into useful products and measurable outcomes.</p><h2>Best-fit students</h2><p>This career suits students who like strategy, communication, research and structured decision-making. Good routes include <a href="/courses/btech">B.Tech</a>, <a href="/courses/bba">BBA</a>, <a href="/courses/mba">MBA</a> and analytics-led programmes.</p><h2>Skills to build first</h2><p>Focus on user research, product analytics, prioritisation, writing, design thinking, stakeholder management and business metrics. Build case studies that show how you think.</p><h2>Career outlook</h2><p>Product roles are common in SaaS, fintech, consumer apps, edtech, ecommerce and AI products. Freshers often enter through associate product manager, business analyst or growth roles.</p><h2>FAQ</h2><h3>Is coding required for product management?</h3><p>Coding is not mandatory, but technical understanding helps you work better with engineering teams.</p><h3>Is MBA required?</h3><p>No, but an MBA can help for business-heavy PM roles.</p>$career$,
    'Product Manager is a strong career for students who like users, strategy, analytics and technology. Build case studies, product thinking and clear communication.',
    '₹10 - 45 LPA',
    'High',
    '0 - 2 years for associate PM paths; 3+ years for core PM roles',
    ARRAY['Product Strategy','User Research','Analytics','Prioritisation','Communication','Design Thinking','Business Metrics'],
    ARRAY['Google','Microsoft','Razorpay','Swiggy','Flipkart','Zomato','Freshworks'],
    ARRAY['btech','bba','mba'],
    ARRAY['cat','xat','cuet'],
    '[{"title":"Associate Product Manager","level":"Entry"},{"title":"Product Analyst","level":"Entry"},{"title":"Product Manager","level":"Mid"},{"title":"Growth Product Manager","level":"Mid"}]'::jsonb,
    '🎯',
    'Product Manager Career Scope 2026',
    'Explore Product Manager salary, skills, courses, exams and job roles for Indian students.',
    'product manager career, APM jobs India, product management salary, MBA product roles',
    true,
    6
  ),
  (
    'ui-ux-designer',
    'UI UX Designer',
    'Design',
    'UI UX Designers create digital experiences that are useful, clear and easy to use.',
    $career$<h2>What does a UI UX Designer do?</h2><p>A UI UX Designer researches users, maps journeys, creates wireframes, designs interfaces and tests usability. The career is popular because every app, website and AI product needs a clean experience that real people can understand.</p><h2>Best-fit students</h2><p>This role suits students who enjoy design, psychology, storytelling and problem solving. Relevant paths include <a href="/courses/bdes">B.Des</a>, design diplomas, <a href="/courses/btech">B.Tech</a> with product interest and self-built portfolios.</p><h2>Skills to build first</h2><p>Learn user research, information architecture, Figma, visual hierarchy, prototyping, accessibility and design systems. A portfolio should explain the problem and decision process, not only show screens.</p><h2>Career outlook</h2><p>Demand is strong in product companies, design studios, fintech, ecommerce, SaaS and edtech. Entry roles include UI designer, UX researcher, product designer intern and interaction designer.</p><h2>FAQ</h2><h3>Is drawing compulsory?</h3><p>No. Clear thinking, user empathy and interface judgment matter more than hand drawing.</p><h3>What should my portfolio include?</h3><p>Show research, problem framing, wireframes, final screens and what changed after feedback.</p>$career$,
    'UI UX Designer is a popular career for students who want to design useful digital products. Build Figma, research, prototyping, accessibility and portfolio case studies.',
    '₹4 - 22 LPA',
    'High',
    '0 - 1 year for internships and junior design roles',
    ARRAY['Figma','User Research','Wireframing','Prototyping','Visual Design','Accessibility','Design Systems'],
    ARRAY['Microsoft','Google','PhonePe','Swiggy','MakeMyTrip','Zomato','Designit'],
    ARRAY['bdes','btech','bba'],
    ARRAY['ceed','uceed','nid-dat','cuet'],
    '[{"title":"UI Designer","level":"Entry"},{"title":"UX Designer","level":"Entry"},{"title":"Product Designer","level":"Mid"},{"title":"UX Researcher","level":"Entry to Mid"}]'::jsonb,
    '🎨',
    'UI UX Designer Career Scope 2026',
    'Explore UI UX Designer salary, skills, courses, exams and portfolio path for Indian students.',
    'UI UX designer career, product designer salary, design career India, UCEED CEED',
    true,
    7
  ),
  (
    'digital-marketing-manager',
    'Digital Marketing Manager',
    'Marketing',
    'Digital Marketing Managers grow brands through search, content, social, paid campaigns and analytics.',
    $career$<h2>What does a Digital Marketing Manager do?</h2><p>A Digital Marketing Manager plans and improves campaigns across SEO, content, social media, paid ads, email and analytics. The career is popular because every college, startup, brand and local business needs measurable online growth.</p><h2>Best-fit students</h2><p>This role suits students who enjoy creativity, numbers, writing and consumer behaviour. Useful routes include <a href="/courses/bba">BBA</a>, <a href="/courses/mba">MBA</a>, commerce, mass communication and self-driven campaign projects.</p><h2>Skills to build first</h2><p>Learn SEO, content planning, performance marketing, Google Analytics, social strategy, copywriting, landing pages and conversion tracking. Real campaign results are the best proof.</p><h2>Career outlook</h2><p>Hiring exists in agencies, ecommerce, edtech, D2C brands, SaaS, media and startups. Entry roles include SEO executive, content marketer, performance marketing associate and growth marketer.</p><h2>FAQ</h2><h3>Is digital marketing only social media?</h3><p>No. It includes search, ads, email, analytics, content, conversion and retention.</p><h3>Can freshers start quickly?</h3><p>Yes, if they can show writing, analytics and campaign practice.</p>$career$,
    'Digital Marketing Manager is a strong career for students who like growth, content, SEO, ads and analytics. Build campaigns, dashboards and measurable case studies.',
    '₹3 - 20 LPA',
    'High',
    '0 - 2 years for executive and associate roles',
    ARRAY['SEO','Content Strategy','Performance Marketing','Analytics','Copywriting','Social Media','Conversion Optimisation'],
    ARRAY['Google','Meta','Dentsu','WPP','Nykaa','Myntra','Unacademy'],
    ARRAY['bba','mba','bcom'],
    ARRAY['cat','cuet'],
    '[{"title":"SEO Executive","level":"Entry"},{"title":"Performance Marketing Associate","level":"Entry"},{"title":"Growth Marketer","level":"Mid"},{"title":"Digital Marketing Manager","level":"Mid"}]'::jsonb,
    '📣',
    'Digital Marketing Manager Career Scope 2026',
    'Explore Digital Marketing Manager salary, skills, courses and job roles for Indian students.',
    'digital marketing career, SEO jobs, performance marketing salary, growth marketing India',
    true,
    8
  ),
  (
    'investment-banking-analyst',
    'Investment Banking Analyst',
    'Finance',
    'Investment Banking Analysts support deals, valuations, financial models and capital market transactions.',
    $career$<h2>What does an Investment Banking Analyst do?</h2><p>An Investment Banking Analyst builds financial models, researches companies, prepares pitch books and supports mergers, acquisitions, fundraising and market transactions. It is a competitive career because the work is analytical, high-pressure and closely linked to business decisions.</p><h2>Best-fit students</h2><p>This path suits students with strong finance, Excel, accounting, valuation and communication skills. Common routes include <a href="/courses/bcom">B.Com</a>, <a href="/courses/bba">BBA</a>, <a href="/courses/mba">MBA</a>, CA and economics.</p><h2>Skills to build first</h2><p>Learn financial statements, valuation, Excel modelling, PowerPoint, market research and business writing. Internships and deal-style case studies are important.</p><h2>Career outlook</h2><p>Opportunities exist in investment banks, boutique advisory firms, private equity support, consulting and corporate finance teams. Entry roles are selective and usually require sharp preparation.</p><h2>FAQ</h2><h3>Is MBA compulsory?</h3><p>No, but MBA, CA, economics or strong finance internships can improve access.</p><h3>Is the work intense?</h3><p>Yes. The role often has demanding hours, strict deadlines and high attention to detail.</p>$career$,
    'Investment Banking Analyst is a finance career for students who like valuation, deals, financial modelling and capital markets. Build Excel, accounting, valuation and business writing.',
    '₹8 - 35 LPA',
    'High',
    '0 - 2 years for analyst roles',
    ARRAY['Financial Modelling','Valuation','Accounting','Excel','PowerPoint','Market Research','Business Writing'],
    ARRAY['JP Morgan','Goldman Sachs','Morgan Stanley','Axis Capital','ICICI Securities','EY','Deloitte'],
    ARRAY['bcom','bba','mba'],
    ARRAY['cat','cuet'],
    '[{"title":"Investment Banking Analyst","level":"Entry"},{"title":"Corporate Finance Analyst","level":"Entry"},{"title":"Valuation Analyst","level":"Entry"},{"title":"M&A Analyst","level":"Entry to Mid"}]'::jsonb,
    '🏦',
    'Investment Banking Analyst Career Scope 2026',
    'Explore Investment Banking Analyst salary, skills, courses and job roles for Indian students.',
    'investment banking career, finance analyst, MBA finance jobs, valuation analyst India',
    true,
    9
  ),
  (
    'fintech-analyst',
    'FinTech Analyst',
    'FinTech',
    'FinTech Analysts work at the intersection of finance, technology, payments, lending and risk.',
    $career$<h2>What does a FinTech Analyst do?</h2><p>A FinTech Analyst studies digital payments, lending, credit risk, user behaviour, compliance and product performance. This career is growing because India has a large digital payments ecosystem and fast-moving financial technology companies.</p><h2>Best-fit students</h2><p>This path suits students who like finance, analytics, products and technology. Helpful courses include <a href="/courses/bcom">B.Com</a>, <a href="/courses/bba">BBA</a>, <a href="/courses/mba">MBA</a>, <a href="/courses/btech">B.Tech</a> and analytics programmes.</p><h2>Skills to build first</h2><p>Build SQL, Excel, product analytics, payments basics, credit risk, compliance awareness and dashboarding. Understanding RBI-led digital finance context is useful.</p><h2>Career outlook</h2><p>Roles exist in payments, lending, wealth-tech, insure-tech, banking product teams and risk analytics. Entry paths include product analyst, risk analyst, credit analyst and business analyst.</p><h2>FAQ</h2><h3>Is FinTech only for engineers?</h3><p>No. Commerce, finance, management and analytics students can do well with technical literacy.</p><h3>What should I learn first?</h3><p>Start with finance basics, SQL, Excel and one payments or lending case study.</p>$career$,
    'FinTech Analyst is a modern finance career for students who like payments, lending, analytics and digital products. Build SQL, finance basics, risk and product analytics.',
    '₹5 - 24 LPA',
    'High',
    '0 - 2 years for analyst roles',
    ARRAY['SQL','Excel','Financial Analysis','Risk Analytics','Payments','Product Analytics','Compliance Basics'],
    ARRAY['Razorpay','PhonePe','Paytm','NPCI ecosystem firms','Pine Labs','CRED','Groww'],
    ARRAY['bcom','bba','mba','btech'],
    ARRAY['cat','cuet'],
    '[{"title":"FinTech Analyst","level":"Entry"},{"title":"Product Analyst","level":"Entry"},{"title":"Risk Analyst","level":"Entry"},{"title":"Credit Analyst","level":"Entry to Mid"}]'::jsonb,
    '💳',
    'FinTech Analyst Career Scope 2026',
    'Explore FinTech Analyst salary, skills, courses and job roles for Indian students.',
    'fintech analyst career, payments jobs, risk analyst, product analyst fintech India',
    true,
    10
  ),
  (
    'business-analyst',
    'Business Analyst',
    'Business Analytics',
    'Business Analysts convert business problems into requirements, insights and action plans.',
    $career$<h2>What does a Business Analyst do?</h2><p>A Business Analyst understands stakeholder needs, studies processes, analyses data and helps teams make better decisions. It is a popular career because it connects business, technology, operations and analytics without requiring deep coding from day one.</p><h2>Best-fit students</h2><p>This path suits students who like communication, logic, Excel, dashboards and structured problem solving. Useful routes include <a href="/courses/bba">BBA</a>, <a href="/courses/bcom">B.Com</a>, <a href="/courses/mba">MBA</a>, <a href="/courses/btech">B.Tech</a> and analytics courses.</p><h2>Skills to build first</h2><p>Learn Excel, SQL basics, requirement writing, process mapping, Power BI, stakeholder communication and problem framing. Case studies are very useful for interviews.</p><h2>Career outlook</h2><p>Business analysts are hired in IT services, consulting, SaaS, banking, ecommerce, healthcare and operations teams. It is one of the easiest bridges from college to business-tech roles.</p><h2>FAQ</h2><h3>Is business analyst a technical role?</h3><p>It can be semi-technical. SQL, dashboards and system understanding help a lot.</p><h3>Can freshers become business analysts?</h3><p>Yes. Freshers should show analytical projects, clear writing and strong communication.</p>$career$,
    'Business Analyst is a flexible career for students who like business, data and communication. Build Excel, SQL, dashboards, requirements and case-study thinking.',
    '₹4 - 18 LPA',
    'High',
    '0 - 1 year for associate analyst roles',
    ARRAY['Excel','SQL','Power BI','Requirements','Process Mapping','Communication','Problem Solving'],
    ARRAY['TCS','Infosys','Accenture','Deloitte','EY','Amazon','HDFC Bank'],
    ARRAY['bba','bcom','mba','btech'],
    ARRAY['cat','cuet'],
    '[{"title":"Business Analyst","level":"Entry"},{"title":"Product Analyst","level":"Entry"},{"title":"Operations Analyst","level":"Entry"},{"title":"Consulting Analyst","level":"Entry"}]'::jsonb,
    '📈',
    'Business Analyst Career Scope 2026',
    'Explore Business Analyst salary, skills, courses and job roles for Indian students.',
    'business analyst career, BA jobs India, business analytics, MBA analyst roles',
    true,
    11
  ),
  (
    'renewable-energy-engineer',
    'Renewable Energy Engineer',
    'Clean Energy',
    'Renewable Energy Engineers design and support solar, wind, storage and clean power systems.',
    $career$<h2>What does a Renewable Energy Engineer do?</h2><p>A Renewable Energy Engineer works on solar plants, wind systems, battery storage, energy audits and clean power integration. The career is gaining attention because India is expanding clean energy capacity and companies are tracking sustainability goals.</p><h2>Best-fit students</h2><p>This path suits students who like electrical systems, mechanical systems, environment and field problem solving. Useful routes include <a href="/courses/btech">B.Tech</a> in electrical, mechanical, energy or related engineering branches.</p><h2>Skills to build first</h2><p>Learn electrical basics, solar PV design, power systems, AutoCAD, energy auditing, project management and safety standards. Field internships help a lot.</p><h2>Career outlook</h2><p>Roles exist with renewable developers, EPC companies, consulting firms, utilities and manufacturing companies. Entry roles include solar design engineer, project engineer, energy analyst and O&M engineer.</p><h2>FAQ</h2><h3>Is renewable energy a stable career?</h3><p>It is promising, especially for students who combine engineering basics with project and field exposure.</p><h3>Do I need coding?</h3><p>Not always, but data analysis and simulation tools can improve opportunities.</p>$career$,
    'Renewable Energy Engineer is a clean-energy career for students interested in solar, wind, battery storage and power systems. Build engineering fundamentals and field exposure.',
    '₹4 - 18 LPA',
    'High',
    '0 - 2 years for design, project and O&M roles',
    ARRAY['Solar PV Design','Power Systems','AutoCAD','Energy Audits','Project Management','Safety Standards','Data Analysis'],
    ARRAY['Tata Power Solar','ReNew','Adani Green','L&T','Suzlon','NTPC Renewable Energy'],
    ARRAY['btech','master-of-technology-mtech'],
    ARRAY['jee-main','gate'],
    '[{"title":"Solar Design Engineer","level":"Entry"},{"title":"Renewable Project Engineer","level":"Entry"},{"title":"Energy Analyst","level":"Entry"},{"title":"O&M Engineer","level":"Entry to Mid"}]'::jsonb,
    '🌱',
    'Renewable Energy Engineer Career Scope 2026',
    'Explore Renewable Energy Engineer salary, skills, courses and job roles for Indian students.',
    'renewable energy career, solar engineer, clean energy jobs India, power systems career',
    true,
    12
  ),
  (
    'sustainability-esg-specialist',
    'Sustainability and ESG Specialist',
    'Sustainability',
    'Sustainability and ESG Specialists help organisations measure, report and improve environmental and social impact.',
    $career$<h2>What does a Sustainability and ESG Specialist do?</h2><p>A Sustainability and ESG Specialist works on climate reporting, carbon accounting, responsible sourcing, ESG disclosures and sustainability programmes. The career is growing as companies, investors and regulators pay closer attention to measurable impact.</p><h2>Best-fit students</h2><p>This path suits students who care about environment, policy, business and data. Helpful routes include <a href="/courses/bba">BBA</a>, <a href="/courses/mba">MBA</a>, economics, environmental science, engineering and public policy.</p><h2>Skills to build first</h2><p>Learn ESG frameworks, carbon accounting basics, Excel, data reporting, stakeholder communication, sustainability strategy and policy reading. Strong writing is important.</p><h2>Career outlook</h2><p>Opportunities exist in consulting, manufacturing, finance, real estate, energy, consumer goods and impact organisations. Entry roles include ESG analyst, sustainability analyst and climate reporting associate.</p><h2>FAQ</h2><h3>Is ESG only for environmental science students?</h3><p>No. Business, finance, engineering and policy students can also enter this field.</p><h3>What makes a candidate strong?</h3><p>Data discipline, policy awareness, clear writing and practical project experience.</p>$career$,
    'Sustainability and ESG Specialist is a growing career for students interested in climate, impact, business and reporting. Build ESG, carbon accounting, data and policy skills.',
    '₹5 - 22 LPA',
    'High',
    '0 - 2 years for analyst roles',
    ARRAY['ESG Reporting','Carbon Accounting','Excel','Policy Research','Data Reporting','Stakeholder Communication','Sustainability Strategy'],
    ARRAY['Deloitte','EY','KPMG','PwC','Tata Sustainability Group','Accenture','Sustainalytics'],
    ARRAY['bba','mba','btech','msc'],
    ARRAY['cat','cuet','gate'],
    '[{"title":"ESG Analyst","level":"Entry"},{"title":"Sustainability Analyst","level":"Entry"},{"title":"Climate Reporting Associate","level":"Entry"},{"title":"ESG Consultant","level":"Mid"}]'::jsonb,
    '🌍',
    'Sustainability and ESG Specialist Career Scope 2026',
    'Explore Sustainability and ESG Specialist salary, skills, courses and job roles for Indian students.',
    'ESG career, sustainability jobs India, climate analyst, ESG reporting career',
    true,
    13
  ),
  (
    'healthcare-administrator',
    'Healthcare Administrator',
    'Healthcare Management',
    'Healthcare Administrators manage hospital operations, patient services, teams, quality and compliance.',
    $career$<h2>What does a Healthcare Administrator do?</h2><p>A Healthcare Administrator manages hospital operations, patient flow, quality processes, billing coordination, compliance and service improvement. The career is popular because healthcare needs trained managers, not only doctors and nurses.</p><h2>Best-fit students</h2><p>This path suits students who like healthcare, operations, people management and systems. Helpful routes include <a href="/courses/bba">BBA</a>, <a href="/courses/mba">MBA</a>, hospital administration, public health and allied health programmes.</p><h2>Skills to build first</h2><p>Learn hospital operations, healthcare quality, Excel, communication, patient experience, compliance basics and team coordination. Internships in hospitals are highly valuable.</p><h2>Career outlook</h2><p>Roles exist in hospitals, clinics, health-tech companies, insurance operations and diagnostic chains. Entry roles include operations executive, patient services coordinator and hospital administration trainee.</p><h2>FAQ</h2><h3>Do I need an MBBS?</h3><p>No. Healthcare administration is a management path, though medical knowledge helps.</p><h3>Is this career only in hospitals?</h3><p>No. It also exists in health-tech, diagnostics, insurance and public health operations.</p>$career$,
    'Healthcare Administrator is a management career for students interested in hospitals, patient services, quality and operations. Build healthcare operations and communication skills.',
    '₹4 - 20 LPA',
    'High',
    '0 - 2 years for hospital operations roles',
    ARRAY['Hospital Operations','Healthcare Quality','Patient Experience','Excel','Compliance Basics','Communication','Team Coordination'],
    ARRAY['Apollo Hospitals','Fortis','Max Healthcare','Manipal Hospitals','Narayana Health','Practo'],
    ARRAY['bba','mba','mbbs'],
    ARRAY['cat','cuet','neet-ug'],
    '[{"title":"Hospital Operations Executive","level":"Entry"},{"title":"Patient Services Coordinator","level":"Entry"},{"title":"Healthcare Administrator","level":"Mid"},{"title":"Quality Coordinator","level":"Entry to Mid"}]'::jsonb,
    '🏥',
    'Healthcare Administrator Career Scope 2026',
    'Explore Healthcare Administrator salary, skills, courses and job roles for Indian students.',
    'healthcare administration career, hospital management jobs, MBA healthcare India',
    true,
    14
  ),
  (
    'clinical-research-associate',
    'Clinical Research Associate',
    'Life Sciences',
    'Clinical Research Associates support trials, documentation and compliance for medicines and healthcare products.',
    $career$<h2>What does a Clinical Research Associate do?</h2><p>A Clinical Research Associate supports clinical trials by monitoring sites, checking documentation, coordinating with investigators and ensuring protocol compliance. The career matters because healthcare innovation needs safe, ethical and well-documented research.</p><h2>Best-fit students</h2><p>This path suits students from pharmacy, life sciences, medicine, nursing and biotechnology who like detail, documentation and healthcare research. Useful routes include <a href="/courses/mbbs">MBBS</a>, pharmacy, biotechnology and life science courses.</p><h2>Skills to build first</h2><p>Learn clinical trial basics, GCP, documentation, ethics, pharmacology basics, communication and Excel. Attention to detail is non-negotiable.</p><h2>Career outlook</h2><p>Roles exist in CROs, pharma companies, hospitals, biotech firms and medical device organisations. Entry roles include clinical trial coordinator, research associate and CRA trainee.</p><h2>FAQ</h2><h3>Is this a lab-only career?</h3><p>No. It includes documentation, site monitoring, coordination and compliance work.</p><h3>Who can enter?</h3><p>Students from life sciences, pharmacy, nursing, medicine and allied health backgrounds are common fits.</p>$career$,
    'Clinical Research Associate is a life-sciences career for students interested in clinical trials, research documentation and healthcare compliance.',
    '₹4 - 18 LPA',
    'High',
    '0 - 2 years for coordinator or trainee roles',
    ARRAY['Clinical Trials','GCP','Documentation','Ethics','Pharmacology Basics','Communication','Excel'],
    ARRAY['IQVIA','Parexel','Syneos Health','Novartis','Sun Pharma','Dr. Reddy''s'],
    ARRAY['mbbs','bachelor-of-science-bsc','msc'],
    ARRAY['neet-ug','cuet'],
    '[{"title":"Clinical Trial Coordinator","level":"Entry"},{"title":"Clinical Research Associate","level":"Entry to Mid"},{"title":"Research Associate","level":"Entry"},{"title":"Medical Writing Associate","level":"Entry"}]'::jsonb,
    '🧬',
    'Clinical Research Associate Career Scope 2026',
    'Explore Clinical Research Associate salary, skills, courses and job roles for Indian students.',
    'clinical research career, CRA jobs India, clinical trial coordinator, life science jobs',
    true,
    15
  ),
  (
    'robotics-engineer',
    'Robotics Engineer',
    'Robotics and Automation',
    'Robotics Engineers design intelligent machines, automation systems and mechatronic products.',
    $career$<h2>What does a Robotics Engineer do?</h2><p>A Robotics Engineer works on mechanical design, electronics, sensors, control systems, software and automation. The career is gaining popularity because manufacturing, logistics, healthcare, defence and agriculture are using more automation.</p><h2>Best-fit students</h2><p>This path suits students who like machines, coding, electronics and building physical systems. Strong routes include <a href="/courses/btech">B.Tech</a> in mechanical, electronics, computer science, mechatronics or related engineering.</p><h2>Skills to build first</h2><p>Learn C/C++, Python, control systems, embedded systems, CAD, sensors, ROS basics and electronics. Practical prototypes matter more than theory alone.</p><h2>Career outlook</h2><p>Roles exist in automation companies, manufacturing, drones, robotics startups, industrial IoT and research labs. Entry roles include robotics trainee, automation engineer and embedded systems engineer.</p><h2>FAQ</h2><h3>Is robotics only mechanical engineering?</h3><p>No. Robotics blends mechanical, electronics, computer science and control systems.</p><h3>What project should I build?</h3><p>Start with a line follower, robotic arm, drone subsystem or sensor-based automation project.</p>$career$,
    'Robotics Engineer is a career for students who like machines, electronics, coding and automation. Build prototypes with embedded systems, control and mechanical design.',
    '₹5 - 24 LPA',
    'High',
    '0 - 2 years for trainee and automation roles',
    ARRAY['C++','Python','Embedded Systems','Control Systems','CAD','Sensors','ROS'],
    ARRAY['ABB','KUKA','Tata Elxsi','Bosch','L&T','GreyOrange','Addverb'],
    ARRAY['btech','master-of-technology-mtech'],
    ARRAY['jee-main','gate'],
    '[{"title":"Robotics Engineer","level":"Entry to Mid"},{"title":"Automation Engineer","level":"Entry"},{"title":"Embedded Systems Engineer","level":"Entry"},{"title":"Mechatronics Engineer","level":"Entry to Mid"}]'::jsonb,
    '🦾',
    'Robotics Engineer Career Scope 2026',
    'Explore Robotics Engineer salary, skills, courses and job roles for Indian students.',
    'robotics engineer career, automation jobs India, mechatronics career, embedded systems',
    true,
    16
  ),
  (
    'supply-chain-analyst',
    'Supply Chain Analyst',
    'Operations and Logistics',
    'Supply Chain Analysts improve inventory, logistics, planning, fulfilment and operational decisions.',
    $career$<h2>What does a Supply Chain Analyst do?</h2><p>A Supply Chain Analyst studies demand, inventory, transport, warehouse performance and fulfilment data. The career is important because ecommerce, manufacturing, retail and quick commerce need faster, smarter and more reliable operations.</p><h2>Best-fit students</h2><p>This path suits students who like operations, data, process improvement and practical business problems. Useful routes include <a href="/courses/bba">BBA</a>, <a href="/courses/mba">MBA</a>, engineering and commerce.</p><h2>Skills to build first</h2><p>Learn Excel, SQL, forecasting, inventory basics, logistics metrics, Power BI and process mapping. Understanding real supply chain constraints is a big advantage.</p><h2>Career outlook</h2><p>Hiring exists in ecommerce, FMCG, manufacturing, logistics, retail and consulting. Entry roles include operations analyst, inventory analyst, logistics analyst and planning analyst.</p><h2>FAQ</h2><h3>Is this a desk job or field job?</h3><p>It can be both. Analysts often use data but must understand ground operations.</p><h3>Is MBA useful?</h3><p>Yes, especially for operations, supply chain and consulting roles.</p>$career$,
    'Supply Chain Analyst is a strong career for students interested in operations, logistics, data and business efficiency. Build Excel, SQL, forecasting and process skills.',
    '₹4 - 18 LPA',
    'High',
    '0 - 2 years for analyst roles',
    ARRAY['Excel','SQL','Forecasting','Inventory Management','Logistics Metrics','Power BI','Process Mapping'],
    ARRAY['Amazon','Flipkart','DHL','Delhivery','Reliance Retail','HUL','ITC'],
    ARRAY['bba','mba','btech','bcom'],
    ARRAY['cat','cuet'],
    '[{"title":"Operations Analyst","level":"Entry"},{"title":"Inventory Analyst","level":"Entry"},{"title":"Logistics Analyst","level":"Entry"},{"title":"Supply Chain Analyst","level":"Entry to Mid"}]'::jsonb,
    '🚚',
    'Supply Chain Analyst Career Scope 2026',
    'Explore Supply Chain Analyst salary, skills, courses and job roles for Indian students.',
    'supply chain analyst career, logistics jobs India, operations analyst, MBA operations',
    true,
    17
  ),
  (
    'psychologist-counsellor',
    'Psychologist and Counsellor',
    'Mental Health',
    'Psychologists and Counsellors support mental health, behaviour, learning and emotional wellbeing.',
    $career$<h2>What does a Psychologist and Counsellor do?</h2><p>A Psychologist or Counsellor helps people understand behaviour, emotions, stress, learning difficulties and life decisions. The career is gaining visibility as schools, colleges, workplaces and families take mental health more seriously.</p><h2>Best-fit students</h2><p>This path suits students who are patient, ethical, observant and good listeners. Useful routes include psychology, counselling, <a href="/courses/bachelor-of-science-bsc">B.Sc</a>, <a href="/courses/ma">MA</a> and postgraduate specialisations.</p><h2>Skills to build first</h2><p>Learn psychological foundations, counselling ethics, assessment basics, communication, case documentation and referral boundaries. Supervised training is essential.</p><h2>Career outlook</h2><p>Roles exist in schools, colleges, hospitals, clinics, NGOs, corporate wellbeing and private practice after the required qualifications. Always check licensing and practice rules for the chosen specialisation.</p><h2>FAQ</h2><h3>Can I practise after graduation?</h3><p>Independent practice usually needs higher study, supervised training and compliance with applicable rules.</p><h3>Is this career emotionally demanding?</h3><p>Yes. Self-care, supervision and ethical boundaries are important.</p>$career$,
    'Psychologist and Counsellor is a meaningful career for students interested in mental health, behaviour and wellbeing. Build ethics, supervised training and communication skills.',
    '₹3 - 18 LPA',
    'High',
    'Higher study and supervised practice are usually required',
    ARRAY['Counselling Ethics','Psychological Assessment','Communication','Case Documentation','Empathy','Research Basics','Referral Judgment'],
    ARRAY['Schools','Hospitals','Mental Health Clinics','NGOs','Corporate Wellbeing Teams','EdTech Counselling Teams'],
    ARRAY['bachelor-of-science-bsc','ma','msc','phd'],
    ARRAY['cuet'],
    '[{"title":"School Counsellor","level":"Entry to Mid"},{"title":"Counselling Psychologist","level":"Mid"},{"title":"Clinical Psychologist","level":"Advanced"},{"title":"Mental Health Research Associate","level":"Entry"}]'::jsonb,
    '🧠',
    'Psychologist and Counsellor Career Scope 2026',
    'Explore Psychologist and Counsellor salary, skills, courses and career path for Indian students.',
    'psychologist career India, counselling career, mental health jobs, psychology courses',
    true,
    18
  )
)
INSERT INTO public.career_profiles (
  slug, name, domain, short_description, description, page_summary,
  avg_salary, growth, experience_required, top_skills, top_companies,
  related_courses, related_exams, job_roles, image, icon_emoji,
  meta_title, meta_description, meta_keywords,
  status, is_featured, is_active, display_order, updated_at
)
SELECT
  slug, name, domain, short_description, description, page_summary,
  avg_salary, growth, experience_required, top_skills, top_companies,
  related_courses, related_exams, job_roles, ''::text, icon_emoji,
  meta_title, meta_description, meta_keywords,
  'Published', is_featured, true, display_order, now()
FROM careers
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  domain = EXCLUDED.domain,
  short_description = EXCLUDED.short_description,
  description = EXCLUDED.description,
  page_summary = EXCLUDED.page_summary,
  avg_salary = EXCLUDED.avg_salary,
  growth = EXCLUDED.growth,
  experience_required = EXCLUDED.experience_required,
  top_skills = EXCLUDED.top_skills,
  top_companies = EXCLUDED.top_companies,
  related_courses = EXCLUDED.related_courses,
  related_exams = EXCLUDED.related_exams,
  job_roles = EXCLUDED.job_roles,
  image = '',
  icon_emoji = EXCLUDED.icon_emoji,
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  meta_keywords = EXCLUDED.meta_keywords,
  status = 'Published',
  is_featured = EXCLUDED.is_featured,
  is_active = true,
  display_order = EXCLUDED.display_order,
  updated_at = now();

INSERT INTO public.career_course_links (career_slug, course_slug)
SELECT c.slug, course_slug
FROM careers c
CROSS JOIN LATERAL unnest(c.related_courses) AS course_slug
ON CONFLICT (career_slug, course_slug) DO NOTHING;
