// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { backendFetch, backendTarget, invokeAwsFunction } from '@/lib/backendMode';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (typeof SUPABASE_PUBLISHABLE_KEY === 'string' && SUPABASE_PUBLISHABLE_KEY.startsWith('sb_secret_')) {
  throw new Error('VITE_SUPABASE_PUBLISHABLE_KEY must use a publishable key, not a Supabase secret key.');
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return backendFetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Existing code calls `supabase.functions.invoke(...)`. Intercept that single
// trigger point so every Edge Function gets the same two-switch behaviour.
// Database/Auth/Storage remain on Supabase until they are migrated separately.
export const supabase = new Proxy(supabaseClient, {
  get(target, property, receiver) {
    if (property === 'functions') {
      return new Proxy(target.functions, {
        get(functions, functionProperty, functionReceiver) {
          if (functionProperty === 'invoke') {
            return (name: string, options: { body?: unknown; headers?: HeadersInit; method?: string } = {}) =>
              backendTarget() === 'aws'
                ? invokeAwsFunction(name, options)
                : target.functions.invoke(name, options as never);
          }
          return Reflect.get(functions, functionProperty, functionReceiver);
        },
      });
    }
    return Reflect.get(target, property, receiver);
  },
}) as typeof supabaseClient;
